struct CasoA {id:&'static str,bytes:&'static[u8],estado:&'static str,literal:Option<&'static str>,ruta:Option<[u8;5]>,llamadas:u64,vigente:bool,causa:Option<&'static str>,observados:Option<u64>}
const CASOS_A:&[CasoA]=&[
CasoA{id:"A01",bytes:include_bytes!("publicos/a/A01.json"),estado:"DATO",literal:Some("8.40"),ruta:Some([1,1,1,1,1]),llamadas:1,vigente:true,causa:None,observados:None},
CasoA{id:"A02",bytes:include_bytes!("publicos/a/A02.json"),estado:"DATO",literal:Some("8.40"),ruta:Some([1,1,1,1,1]),llamadas:1,vigente:true,causa:None,observados:None},
CasoA{id:"A03",bytes:include_bytes!("publicos/a/A03.json"),estado:"PETICION_AMBIGUA",literal:None,ruta:None,llamadas:0,vigente:true,causa:None,observados:None},
CasoA{id:"A04",bytes:include_bytes!("publicos/a/A04.json"),estado:"PETICION_AMBIGUA",literal:None,ruta:None,llamadas:0,vigente:false,causa:None,observados:None},
CasoA{id:"A05",bytes:include_bytes!("publicos/a/A05.json"),estado:"DATO",literal:Some("8.40"),ruta:Some([1,1,1,1,1]),llamadas:1,vigente:true,causa:None,observados:None},
CasoA{id:"A06",bytes:include_bytes!("publicos/a/A06.json"),estado:"SOLICITUD_NO_REPRESENTADA",literal:None,ruta:None,llamadas:0,vigente:true,causa:None,observados:None},
CasoA{id:"A07",bytes:include_bytes!("publicos/a/A07.json"),estado:"DATO",literal:Some("Registro artificial; no acredita concentración ni condición clínica."),ruta:Some([1,1,1,1,16]),llamadas:1,vigente:true,causa:None,observados:None},
CasoA{id:"A08",bytes:include_bytes!("publicos/a/A08.json"),estado:"SIN_SOLICITUD_POSITIVA",literal:None,ruta:None,llamadas:0,vigente:true,causa:None,observados:None},
CasoA{id:"A09",bytes:include_bytes!("publicos/a/A09.json"),estado:"A_TRANSPORTE_RECHAZADO",literal:None,ruta:None,llamadas:0,vigente:true,causa:Some("BYTES_LIMITE"),observados:None},
CasoA{id:"A10",bytes:include_bytes!("publicos/a/A10.json"),estado:"A_TRANSPORTE_RECHAZADO",literal:None,ruta:None,llamadas:0,vigente:true,causa:Some("UTF8_INVALIDO"),observados:None},
CasoA{id:"A11",bytes:include_bytes!("publicos/a/A11.json"),estado:"A_TRANSPORTE_RECHAZADO",literal:None,ruta:None,llamadas:0,vigente:true,causa:Some("TRUNCADO"),observados:None},
CasoA{id:"A12",bytes:include_bytes!("publicos/a/A12.json"),estado:"A_TRANSPORTE_RECHAZADO",literal:None,ruta:None,llamadas:0,vigente:true,causa:Some("CLAVE_DUPLICADA"),observados:None},
CasoA{id:"A13",bytes:include_bytes!("publicos/a/A13.json"),estado:"A_TRANSPORTE_RECHAZADO",literal:None,ruta:None,llamadas:0,vigente:true,causa:Some("ESQUEMA_INVALIDO"),observados:None},
CasoA{id:"A14",bytes:include_bytes!("publicos/a/A14.json"),estado:"A_TRANSPORTE_RECHAZADO",literal:None,ruta:None,llamadas:0,vigente:true,causa:Some("ESQUEMA_INVALIDO"),observados:None},
CasoA{id:"A15",bytes:include_bytes!("publicos/a/A15.json"),estado:"A_TRANSPORTE_RECHAZADO",literal:None,ruta:None,llamadas:0,vigente:true,causa:Some("ESQUEMA_INVALIDO"),observados:None},
CasoA{id:"A16",bytes:include_bytes!("publicos/a/A16.json"),estado:"A_TRANSPORTE_RECHAZADO",literal:None,ruta:None,llamadas:0,vigente:true,causa:Some("ENTERO_O_DIMENSION_INVALIDA"),observados:None},
CasoA{id:"A17",bytes:include_bytes!("publicos/a/A17.json"),estado:"DATO",literal:Some("8.40"),ruta:Some([1,1,1,1,1]),llamadas:1,vigente:true,causa:None,observados:None},
CasoA{id:"A18",bytes:include_bytes!("publicos/a/A18.json"),estado:"A_TRANSPORTE_RECHAZADO",literal:None,ruta:None,llamadas:0,vigente:true,causa:Some("JSON_INVALIDO"),observados:None},
CasoA{id:"A19",bytes:include_bytes!("publicos/a/A19.json"),estado:"DATO",literal:Some("8.40"),ruta:Some([1,1,1,1,1]),llamadas:1,vigente:true,causa:None,observados:None},
CasoA{id:"A20",bytes:include_bytes!("publicos/a/A20.json"),estado:"A_TRANSPORTE_RECHAZADO",literal:None,ruta:None,llamadas:0,vigente:true,causa:Some("BYTES_LIMITE"),observados:Some(65537)},
CasoA{id:"A21",bytes:include_bytes!("publicos/a/A21.json"),estado:"A_TRANSPORTE_RECHAZADO",literal:None,ruta:None,llamadas:0,vigente:true,causa:Some("JSON_INVALIDO"),observados:None},
CasoA{id:"A22",bytes:include_bytes!("publicos/a/A22.json"),estado:"A_TOKENS_LIMITE",literal:None,ruta:None,llamadas:0,vigente:true,causa:None,observados:None},
CasoA{id:"A23",bytes:include_bytes!("publicos/a/A23.json"),estado:"CONTEXTO_INSUFICIENTE",literal:None,ruta:None,llamadas:0,vigente:true,causa:None,observados:None},
];
struct CasoV{id:&'static str,bytes:&'static[u8],original:usize,estado:&'static str,causa:Option<&'static str>,cupo:u64,observados:Option<u64>}
const CASOS_V:&[CasoV]=&[
CasoV{id:"V01",bytes:include_bytes!("publicos/v/V01.json"),original:0,estado:"V_AUSENTE",causa:None,cupo:1000000,observados:None},
CasoV{id:"V02",bytes:include_bytes!("publicos/v/V02.json"),original:0,estado:"DERIVACION_SINTACTICA_COMPROBADA",causa:None,cupo:1000000,observados:None},
CasoV{id:"V03",bytes:include_bytes!("publicos/v/V03.json"),original:0,estado:"DERIVACION_SINTACTICA_COMPROBADA",causa:None,cupo:1000000,observados:None},
CasoV{id:"V04",bytes:include_bytes!("publicos/v/V04.json"),original:0,estado:"V_RECHAZADA",causa:Some("TRUNCADO"),cupo:1000000,observados:None},
CasoV{id:"V05",bytes:include_bytes!("publicos/v/V05.json"),original:0,estado:"V_RECHAZADA",causa:Some("BYTES_LIMITE"),cupo:1000000,observados:Some(262145)},
CasoV{id:"V06",bytes:include_bytes!("publicos/v/V06.json"),original:0,estado:"V_RECHAZADA",causa:Some("PRESUPUESTO_AGOTADO"),cupo:1,observados:None},
CasoV{id:"V07",bytes:include_bytes!("publicos/v/V07.json"),original:0,estado:"V_RECHAZADA",causa:Some("CORRELACION_INVALIDA"),cupo:1000000,observados:None},
CasoV{id:"V08",bytes:include_bytes!("publicos/v/V08.json"),original:0,estado:"V_RECHAZADA",causa:Some("CORRELACION_INVALIDA"),cupo:1000000,observados:None},
CasoV{id:"V09",bytes:include_bytes!("publicos/v/V09.json"),original:0,estado:"V_RECHAZADA",causa:Some("CORRELACION_INVALIDA"),cupo:1000000,observados:None},
CasoV{id:"V10",bytes:include_bytes!("publicos/v/V10.json"),original:0,estado:"V_RECHAZADA",causa:Some("CORRELACION_INVALIDA"),cupo:1000000,observados:None},
CasoV{id:"V11",bytes:include_bytes!("publicos/v/V11.json"),original:0,estado:"V_RECHAZADA",causa:Some("CERTIFICADO_INVALIDO"),cupo:1000000,observados:None},
CasoV{id:"V12",bytes:include_bytes!("publicos/v/V12.json"),original:0,estado:"V_RECHAZADA",causa:Some("CERTIFICADO_INVALIDO"),cupo:1000000,observados:None},
CasoV{id:"V13",bytes:include_bytes!("publicos/v/V13.json"),original:0,estado:"V_RECHAZADA",causa:Some("CERTIFICADO_INVALIDO"),cupo:1000000,observados:None},
CasoV{id:"V14",bytes:include_bytes!("publicos/v/V14.json"),original:0,estado:"V_RECHAZADA",causa:Some("CERTIFICADO_INVALIDO"),cupo:1000000,observados:None},
CasoV{id:"V15",bytes:include_bytes!("publicos/v/V15.json"),original:0,estado:"V_RECHAZADA",causa:Some("CERTIFICADO_INVALIDO"),cupo:1000000,observados:None},
CasoV{id:"V16",bytes:include_bytes!("publicos/v/V16.json"),original:0,estado:"V_RECHAZADA",causa:Some("CERTIFICADO_INVALIDO"),cupo:1000000,observados:None},
CasoV{id:"V17",bytes:include_bytes!("publicos/v/V17.json"),original:0,estado:"V_RECHAZADA",causa:Some("CERTIFICADO_INVALIDO"),cupo:1000000,observados:None},
CasoV{id:"V18",bytes:include_bytes!("publicos/v/V18.json"),original:0,estado:"V_RECHAZADA",causa:Some("MEMORIA_LIMITE"),cupo:1000000,observados:None},
CasoV{id:"V19",bytes:include_bytes!("publicos/v/V19.json"),original:0,estado:"V_RECHAZADA",causa:Some("MEMORIA_LIMITE"),cupo:1000000,observados:None},
CasoV{id:"V20",bytes:include_bytes!("publicos/v/V20.json"),original:0,estado:"V_RECHAZADA",causa:Some("ESQUEMA_INVALIDO"),cupo:1000000,observados:None},
CasoV{id:"V21",bytes:include_bytes!("publicos/v/V21.json"),original:0,estado:"V_RECHAZADA",causa:Some("PROFUNDIDAD_LIMITE"),cupo:1000000,observados:None},
CasoV{id:"V22",bytes:include_bytes!("publicos/v/V22.json"),original:0,estado:"V_RECHAZADA",causa:Some("CLAVE_DUPLICADA"),cupo:1000000,observados:None},
CasoV{id:"V23",bytes:include_bytes!("publicos/v/V23.json"),original:0,estado:"V_RECHAZADA",causa:Some("UTF8_INVALIDO"),cupo:1000000,observados:None},
CasoV{id:"V24",bytes:include_bytes!("publicos/v/V24.json"),original:6,estado:"DERIVACION_SINTACTICA_COMPROBADA",causa:None,cupo:1000000,observados:None},
CasoV{id:"V25",bytes:include_bytes!("publicos/v/V25.json"),original:6,estado:"V_RECHAZADA",causa:Some("CERTIFICADO_INVALIDO"),cupo:1000000,observados:None},
];
const LOTE_SHA:&str="130cab8f788867a5dc984741a31812c8193fdd508d8349d1e36c9099b4c3006d";
