use super::*;
const INPUT:&[u8]=include_bytes!("fixtures/solicitud-a01.bin");
const FRAME:&[u8]=include_bytes!("fixtures/marco-a01.bin");
const TRACE:&[u8]=include_bytes!("fixtures/traza-a01.bin");
const PROP:&[u8]=include_bytes!("fixtures/propuesta-v02.bin");
const ANNEX:&[u8]=include_bytes!("fixtures/anexo-v02.bin");
const LOTE:[u8;64]=*b"130cab8f788867a5dc984741a31812c8193fdd508d8349d1e36c9099b4c3006d";
fn identidad()->Realizacion{fn h(k:&str)->[u8;32]{let s=std::env::var(k).expect("huella del conductor");assert_eq!(s.len(),64);let mut out=[0;32];for i in 0..32{out[i]=u8::from_str_radix(&s[i*2..i*2+2],16).unwrap();}out}Realizacion{fuentes_sha256:h("G1_FUENTES_SHA256"),binario_sha256:h("G1_BINARIO_SHA256")}}
fn guardar(c:&Custodio,h:&Manejador,id:&str){let root=std::path::PathBuf::from(std::env::var("G1_CAPTURAS").unwrap()).join(id);std::fs::create_dir(&root).unwrap();for (name,p)in[("entrada",Papel::Entrada),("marco",Papel::Marco),("traza",Papel::Traza),("propuesta",Papel::Propuesta),("anexo",Papel::Anexo)]{if let Ok(b)=c.recuperar(h,p){std::fs::write(root.join(name),b).unwrap();}}}
fn cust()->Custodio{Custodio::nuevo(identidad()).unwrap()}
fn opened()->(Custodio,Manejador){let mut c=cust();let h=c.abrir(&mut INPUT,true).unwrap();(c,h)}
fn ready()->(Custodio,Manejador){let(mut c,h)=opened();c.ejecutar_a(&h).unwrap();assert_eq!(c.recuperar(&h,Papel::Marco).unwrap(),FRAME);assert_eq!(c.recuperar(&h,Papel::Traza).unwrap(),TRACE);(c,h)}
fn same_a(c:&Custodio,h:&Manejador){assert_eq!(c.recuperar(h,Papel::Marco).unwrap(),FRAME);assert_eq!(c.recuperar(h,Papel::Traza).unwrap(),TRACE);assert_eq!(c.estado(h).unwrap().0,EstadoA::Completa);}
fn witness(id:&str){println!("TESTIGO_G1:{id}:CONFORME_EN_ALCANCE");}
#[test]fn g1_01(){let(c,h)=ready();assert_eq!(c.recibo(&h).unwrap().cuerpo().unwrap(),include_bytes!("fixtures/cuerpo-a01.bin"));assert_eq!(c.identidad(&h).unwrap().1,1);assert!(c.reservas()<=MAX_MEMORY);let(a,v)=c.recibo(&h).unwrap().trabajo();println!("CUENTAS_A01:reservas={},trabajo_a={},trabajo_v={}",c.reservas(),a,v);guardar(&c,&h,"G1-01");witness("G1-01");}
#[test]fn g1_02(){let(mut c,h)=opened();assert_eq!(c.cerrar_a(&h,FRAME.to_vec(),vec![]),Err(Fallo::Json));assert!(matches!(c.estado(&h).unwrap().0,EstadoA::Incompleta(_)));witness("G1-02");}
#[test]fn g1_03(){let(mut c,h)=opened();assert_eq!(c.cerrar_a(&h,FRAME.to_vec(),include_bytes!("fixtures/traza-truncada.bin").to_vec()),Err(Fallo::Json));witness("G1-03");}
#[test]fn g1_04(){let mut c=cust();let h=c.abrir(&mut &include_bytes!("fixtures/solicitud-espacio.bin")[..],true).unwrap();assert_eq!(c.cerrar_a(&h,FRAME.to_vec(),TRACE.to_vec()),Err(Fallo::Correlacion));witness("G1-04");}
#[test]fn g1_05(){let(mut c,h)=opened();assert_eq!(c.cerrar_a(&h,FRAME.to_vec(),include_bytes!("fixtures/traza-discordante.bin").to_vec()),Err(Fallo::Discordancia));witness("G1-05");}
#[test]fn g1_06(){let(mut c,h)=opened();assert_eq!(c.cerrar_a(&h,include_bytes!("fixtures/marco-alterado.bin").to_vec(),TRACE.to_vec()),Err(Fallo::Integridad));witness("G1-06");}
#[test]fn g1_07(){let(mut c,h)=opened();c.perder_traza=true;assert_eq!(c.cerrar_a(&h,FRAME.to_vec(),TRACE.to_vec()),Err(Fallo::Recuperacion));assert_eq!(c.estado(&h).unwrap().0,EstadoA::Incompleta(Fallo::Recuperacion));witness("G1-07");}
#[test]fn g1_08(){let(mut c,h)=ready();assert_eq!(c.cerrar_a(&h,FRAME.to_vec(),TRACE.to_vec()),Err(Fallo::Duplicado));same_a(&c,&h);witness("G1-08");}
#[test]fn g1_09(){let(_c,h)=opened();let(mut c2,h2)=opened();assert_eq!(c2.cerrar_a(&h,FRAME.to_vec(),TRACE.to_vec()),Err(Fallo::Pertenencia));c2.ejecutar_a(&h2).unwrap();same_a(&c2,&h2);witness("G1-09");}
#[test]fn g1_10(){let(mut c,h)=ready();c.iniciar_v(&h,LOTE).unwrap();c.ejecutar_v(&h,&mut PROP).unwrap();assert_eq!(c.recuperar(&h,Papel::Anexo).unwrap(),ANNEX);assert_eq!(c.estado(&h).unwrap().1,EstadoV::Recuperable);same_a(&c,&h);guardar(&c,&h,"G1-10");witness("G1-10");}
#[test]fn g1_11(){let(mut c,h)=ready();c.iniciar_v(&h,LOTE).unwrap();c.ejecutar_v(&h,&mut &include_bytes!("fixtures/propuesta-v04.bin")[..]).unwrap();assert_eq!(c.recuperar(&h,Papel::Anexo).unwrap(),include_bytes!("fixtures/anexo-v04.bin"));assert_eq!(c.estado(&h).unwrap().1,EstadoV::Recuperable);same_a(&c,&h);guardar(&c,&h,"G1-11");witness("G1-11");}
#[test]fn g1_12(){let(mut c,h)=ready();c.iniciar_v(&h,LOTE).unwrap();/* Supervisor informa plazo agotado antes del EOF. No se ensaya su reloj. */c.interrumpir_v(&h).unwrap();assert_eq!(c.estado(&h).unwrap().1,EstadoV::Incompleta(Fallo::Interrupcion));assert_eq!(c.ejecutar_v(&h,&mut PROP),Err(Fallo::Estado));same_a(&c,&h);witness("G1-12");}
#[test]fn g1_13(){let(mut c,h)=ready();c.iniciar_v(&h,LOTE).unwrap();let p=c.archivo(PROP.to_vec(),MAX_V,true).unwrap();c.slots[h.slot].as_mut().unwrap().propuesta=Some(p);assert_eq!(c.cerrar_v(&h,include_bytes!("fixtures/anexo-otro-cuerpo.bin").to_vec()),Err(Fallo::Correlacion));same_a(&c,&h);witness("G1-13");}
#[test]fn g1_14(){let(mut c,h)=ready();c.iniciar_v(&h,LOTE).unwrap();c.ejecutar_v(&h,&mut PROP).unwrap();assert_eq!(c.cerrar_v(&h,ANNEX.to_vec()),Err(Fallo::Duplicado));assert_eq!(c.recuperar(&h,Papel::Anexo).unwrap(),ANNEX);same_a(&c,&h);witness("G1-14");}
#[test]fn g1_15(){let(mut c,h)=opened();assert_eq!(c.iniciar_v(&h,LOTE),Err(Fallo::Estado));assert_eq!(c.cerrar_v(&h,ANNEX.to_vec()),Err(Fallo::Estado));assert_eq!(c.estado(&h).unwrap().0,EstadoA::Abierta);witness("G1-15");}
#[test]fn g1_16(){let(mut c,h)=ready();c.no_solicitar_v(&h).unwrap();assert_eq!(c.estado(&h).unwrap().1,EstadoV::NoSolicitada);same_a(&c,&h);witness("G1-16");}
#[test]fn g1_17(){let mut c=cust();let h=c.abrir(&mut INPUT,false).unwrap();assert_eq!(c.cerrar_a(&h,FRAME.to_vec(),TRACE.to_vec()),Err(Fallo::Montaje));witness("G1-17");}
#[test]fn g1_18(){let mut c=cust();let bytes=vec![b' ';MAX_A+1];let h=c.abrir(&mut &bytes[..],true).unwrap();assert_eq!(c.estado(&h).unwrap().0,EstadoA::Incompleta(Fallo::Limite));assert_eq!(c.recuperar(&h,Papel::Entrada).unwrap().len(),MAX_A);assert!(!c.slots[h.slot].as_ref().unwrap().original.completo);assert!(c.recibo(&h).is_err());witness("G1-18");}
#[test]fn g1_19(){let mut c=cust();let h=c.abrir(&mut &b"{"[..],true).unwrap();c.ejecutar_a(&h).unwrap();let r=c.recibo(&h).unwrap();let txt=std::str::from_utf8(r.cuerpo().unwrap()).unwrap();assert!(txt.contains("A_TRANSPORTE_RECHAZADO"));assert_eq!(r.estado_a(),EstadoA::Completa);println!("PUBLICO_RECHAZO_A:{}",txt.trim());guardar(&c,&h,"G1-19");witness("G1-19");}
#[test]fn g1_20(){let mut input=String::from_utf8(INPUT.to_vec()).unwrap();let question="a ".repeat(128)+".";input=input.replace("El valor de la IgG.",&question).replace("PUBLICO-A01","PUBLICO-TECNICO");let mut c=cust();let h=c.abrir(&mut input.as_bytes(),true).unwrap();c.ejecutar_a(&h).unwrap();let r=c.recibo(&h).unwrap();assert_eq!(r.estado_a(),EstadoA::Completa);assert!(std::str::from_utf8(r.cuerpo().unwrap()).unwrap().contains("A_TOKENS_LIMITE"));println!("PUBLICO_TECNICO_A:{}",std::str::from_utf8(r.cuerpo().unwrap()).unwrap().trim());guardar(&c,&h,"G1-20");witness("G1-20");}
#[test]fn frontera_entrada(){for n in [MAX_A-1,MAX_A,MAX_A+1]{let mut c=cust();let b=vec![b' ';n];let h=c.abrir(&mut &b[..],true).unwrap();assert_eq!(c.estado(&h).unwrap().0,if n>MAX_A{EstadoA::Incompleta(Fallo::Limite)}else{EstadoA::Abierta});}}
#[test]fn frontera_v(){for n in [MAX_V-1,MAX_V,MAX_V+1]{let(mut c,h)=ready();c.iniciar_v(&h,LOTE).unwrap();let b=vec![b' ';n];let result=c.ejecutar_v(&h,&mut &b[..]);if n>MAX_V{assert_eq!(result,Err(Fallo::Limite));}else{assert!(result.is_ok());assert_eq!(c.estado(&h).unwrap().1,EstadoV::Recuperable);}}}
#[test]fn frontera_traza(){for n in [MAX_TRACE-1,MAX_TRACE,MAX_TRACE+1]{let mut c=cust();let r=c.archivo(vec![b' ';n],MAX_TRACE,true);assert_eq!(r.is_ok(),n<=MAX_TRACE);}}
#[test]fn frontera_cuentas(){let mut c=cust();c.cargo(MAX_MEMORY).unwrap();assert_eq!(c.cargo(1),Err(Fallo::Limite));assert_eq!(c.reservas(),MAX_MEMORY);let mut t=Trabajo::nuevo();t.cobrar(MAX_WORK).unwrap();assert_eq!(t.cobrar(1),Err(Fallo::Trabajo));assert_eq!(t.usado,MAX_WORK);}
#[test]fn frontera_slots_ordinal(){let mut c=cust();for _ in 0..4{c.abrir(&mut INPUT,true).unwrap();}assert_eq!(c.abrir(&mut INPUT,true).unwrap_err(),Fallo::Limite);let mut c=cust();c.siguiente=u64::MAX;assert_eq!(c.abrir(&mut INPUT,true).unwrap_err(),Fallo::Ordinal);assert_eq!(c.siguiente,u64::MAX);assert!(std::mem::size_of::<Custodio>()<=65536);}
#[test]fn frontera_json(){for x in [b"{\"a\":1,\"a\":2}".as_slice(),b"{}x",b"\"\\uD800\"",b"\"\\q\"",b"{\"\\u0061\":1}"]{assert!(Vista::nueva(x,&mut Trabajo::nuevo()).is_err());}for n in [96,97]{let b="[".repeat(n)+"0"+&"]".repeat(n);assert_eq!(Vista::nueva(b.as_bytes(),&mut Trabajo::nuevo()).is_ok(),n==96);}let b="[".to_owned()+&vec!["0";9000].join(",")+"]";assert!(Vista::nueva(b.as_bytes(),&mut Trabajo::nuevo()).is_ok());}
#[test]fn perdida_posterior(){let(mut c,h)=ready();c.slots[h.slot].as_mut().unwrap().traza.as_mut().unwrap().b=None;assert_eq!(c.estado(&h).unwrap().0,EstadoA::Completa);assert!(matches!(c.recibo(&h),Err(Fallo::Recuperacion)));}
#[test]fn adversarial_io_v_conserva_prefijo(){struct Cortado{paso:bool}impl Read for Cortado{fn read(&mut self,b:&mut[u8])->std::io::Result<usize>{if self.paso{return Err(std::io::Error::other("corte inyectado"))}self.paso=true;b[..3].copy_from_slice(b"abc");Ok(3)}}let(mut c,h)=ready();c.iniciar_v(&h,LOTE).unwrap();assert_eq!(c.ejecutar_v(&h,&mut Cortado{paso:false}),Err(Fallo::Io));assert_eq!(c.recuperar(&h,Papel::Propuesta).unwrap(),b"abc");assert!(!c.slots[h.slot].as_ref().unwrap().propuesta.as_ref().unwrap().completo);same_a(&c,&h);}
#[test]fn adversarial_contador_nulo(){let(mut c,h)=opened();let trace=std::str::from_utf8(TRACE).unwrap().replace("\"unidades_a\":6104","\"unidades_a\":null");assert_ne!(trace.as_bytes(),TRACE);assert_eq!(c.cerrar_a(&h,FRAME.to_vec(),trace.into_bytes()),Err(Fallo::Esquema));}
