use std::{fs,io::Write,path::{Path,PathBuf},process::{Command,Stdio}};
use serde_json::{json,Value}; use sha2::{Digest,Sha256};
type R<T>=Result<T,Box<dyn std::error::Error>>;
fn hash(b:&[u8])->String{format!("{:x}",Sha256::digest(b))}
fn txt<'a>(v:&'a Value,k:&str)->&'a str{v[k].as_str().unwrap()}
fn write(p:&Path,b:&[u8])->R<()>{fs::create_dir_all(p.parent().unwrap())?;let mut f=fs::OpenOptions::new().write(true).create_new(true).open(p)?;f.write_all(b)?;Ok(())}
fn save(p:&Path,v:&Value)->R<()>{write(p,(serde_json::to_string_pretty(v)?+"\n").as_bytes())}
fn api(ep:&str,method:&str,body:Option<&Value>)->R<Value>{let mut c=Command::new("gh");c.args(["api",ep,"--method",method]);if body.is_some(){c.args(["--input","-"]);}let mut p=c.stdin(Stdio::piped()).stdout(Stdio::piped()).stderr(Stdio::piped()).spawn()?;if let Some(b)=body{p.stdin.take().unwrap().write_all(&serde_json::to_vec(b)?)?;}else{p.stdin.take();}let o=p.wait_with_output()?;if !o.status.success(){return Err(format!("GitHub: {}",String::from_utf8_lossy(&o.stderr)).into())}Ok(serde_json::from_slice(&o.stdout)?)}
fn decode(s:&str)->R<Vec<u8>>{let(mut n,mut bits)=(0u32,0u32);let mut o=vec![];for c in s.bytes(){let v=match c{b'A'..=b'Z'=>c-b'A',b'a'..=b'z'=>c-b'a'+26,b'0'..=b'9'=>c-b'0'+52,b'+'=>62,b'/'=>63,b'='=>break,b'\n'|b'\r'|b' '|b'\t'=>continue,_=>return Err("base64".into())};n=(n<<6)|v as u32;bits+=6;if bits>=8{bits-=8;o.push((n>>bits)as u8);n&=(1<<bits)-1}}Ok(o)}
fn csv(s:&str)->Vec<Vec<String>>{let(mut rows,mut row,mut field,mut q)=(vec![],vec![],String::new(),false);let mut it=s.chars().peekable();while let Some(c)=it.next(){match c{'"'=>{if q&&it.peek()==Some(&'"'){field.push('"');it.next();}else{q=!q;}},',' if !q=>{row.push(std::mem::take(&mut field));},'\n' if !q=>{row.push(std::mem::take(&mut field));rows.push(std::mem::take(&mut row));},'\r' if !q=>{},_=>field.push(c)}}assert!(!q);if !field.is_empty()||!row.is_empty(){row.push(field);rows.push(row)}rows}
fn prepare(st:&Path)->R<()>{
 assert_eq!(hash(b"abc"),"ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad");assert_eq!(decode("YWJj")?,b"abc");
 let p:Value=serde_json::from_slice(&fs::read(st.join("PLAN-FINAL.json"))?)?;let files=p["archivos"].as_array().unwrap();assert_eq!(files.len(),18);let mut manifest=vec![];
 for f in files{let repo=txt(f,"repo");assert!(["SV-motor","SV-sala-de-maquinas","SV-lenguaje-de-computacion"].contains(&repo));let path=txt(f,"path");assert!(!path.contains("..")&&!path.starts_with('/'));let s=txt(f,"content");assert!(!s.contains('\u{fffd}'));if path.ends_with(".json"){let _:Value=serde_json::from_str(s)?;}
 if path.ends_with(".md"){assert!(s.contains(txt(&p,"autoria_licencia")));} if !f["original"].is_null(){assert_ne!(s,txt(f,"original"),"Documento sin actualización: {path}");}
 if txt(f,"mode")=="append"{assert!(s.starts_with(txt(f,"original")),"Antecedente alterado: {path}");}
 if txt(f,"mode")=="insert"{let foot=txt(&p,"autoria_licencia");let old=txt(f,"original");let k=old.rfind(foot).unwrap();assert!(s.starts_with(&old[..k]));assert!(s.ends_with(&old[k..]));}
 if path.ends_with("SUCESOS_SV.md"){let old=txt(f,"original");let a=old.find("## S39").unwrap();let b=old.find("## S40").unwrap();assert!(s.starts_with(&old[..a])&&s.ends_with(&old[b..]));}
 if path.ends_with("SUCESOS_SV.csv")&&!path.contains("HISTORIAL"){let a=csv(txt(f,"original"));let b=csv(s);assert_eq!(a.len(),b.len());for(x,y)in a.iter().zip(&b){if x[0]!="S39"{assert_eq!(x,y);}}}
 let rel=format!("{repo}/{path}");write(&st.join("revisados-final").join(&rel),s.as_bytes())?;manifest.push(json!({"ruta":rel,"bytes":s.len(),"sha256":hash(s.as_bytes()),"original_blob":f["original_blob"]}));
 }
 let get=|suffix:&str|->&str{txt(files.iter().find(|f|txt(f,"path").ends_with(suffix)).unwrap(),"content")};
 let s=csv(get("/SUCESOS_SV.csv"));let h=csv(get("HISTORIAL_SUCESOS_SV.csv"));let sr=s.iter().find(|r|r[0]=="S39").unwrap();let last=h.last().unwrap();assert_eq!(last[0],"39");assert_eq!(&last[1..],sr.as_slice());
 let oldh=csv(txt(files.iter().find(|f|txt(f,"path").ends_with("HISTORIAL_SUCESOS_SV.csv")).unwrap(),"original"));assert_eq!(oldh.iter().filter(|r|r.get(1).map(String::as_str)==Some("S39")).last().unwrap()[0],"38");
 let t=csv(get("TIQUES_TECNICOS.csv"));assert_eq!(t.iter().filter(|r|r.get(1).map(String::as_str)==Some("TT-0020")).count(),1);assert_eq!(t.last().unwrap()[3],"pendiente");
 let tj:Value=serde_json::from_str(get("TT-0020_CALCULO_RUST_AMD_2026-10-05.json"))?;assert_eq!(tj["estado"],"pendiente");assert_eq!(tj["revision_suceso"],39);assert_eq!(tj["recepcion_finalizada"],false);
 let fj:Value=serde_json::from_str(get("/FUENTES.json"))?;for(expected,authors,m)in [(90,19,&fj["muestras"][0]),(11,2,&fj["muestras"][1])]{assert_eq!(m["total"],expected);assert_eq!(m["cuentas_autoras_distintas"],authors);assert_eq!(m["incomplete_results"],false);let ids=m["propuestas"].as_array().unwrap();assert_eq!(ids.len(),expected as usize);let mut unique=std::collections::HashSet::new();for i in ids{assert!(unique.insert(i.as_u64().unwrap()));}}
 let ver:Value=serde_json::from_str(get("VERSIONES.json"))?;assert_eq!(ver["edicion_documental"],"2.23");assert!(get("ACTA_004_FINALIDAD_ALCANCE_Y_CONTINUIDAD_EIO_2026_09_22.md").contains("## 33."));
 let ret=csv(get("REGISTRO_EVOLUCION_TECNICA_PROYECTO.csv"));assert_eq!(ret.last().unwrap()[0],"RETP-2026-278");
 let source=fs::read(st.join("control.rs"))?;let cpath="SV-lenguaje-de-computacion/docs/calidad/tuberias-ia/continuacion-15-09-2026/CONTROL_INCORPORACION_CALCULO_RUST_20261005.rs";
 write(&st.join("revisados-final").join(cpath),&source)?;manifest.push(json!({"ruta":cpath,"bytes":source.len(),"sha256":hash(&source),"original_blob":null}));
 let check=json!({"expediente":p["expediente"],"estado":"CONFORME_DOCUMENTAL","alcance":["Concordancia S39 CSV, historial y referencias","Antecedentes de historial y RETP preservados","Otros sucesos intactos","TT-0020 pendiente y único, JSON y CSV concordantes","EIO 2.23 y Acta 004 sección 33","Recuentos y unicidad de propuestas de mantenimiento","UTF-8, JSON, bytes y SHA-256 Rust"],"limites":"No prueba GPU, exactitud numérica o inferencia; publicación remota cotejada en constancias posteriores","bases_consultadas":p["bases"],"archivos":manifest,"autoria_licencia":p["autoria_licencia"]});
 let b=(serde_json::to_string_pretty(&check)?+"\n").into_bytes();let cp="SV-lenguaje-de-computacion/docs/calidad/tuberias-ia/continuacion-15-09-2026/CONTROL_INCORPORACION_CALCULO_RUST_20261005.json";write(&st.join("revisados-final").join(cp),&b)?;manifest.push(json!({"ruta":cp,"bytes":b.len(),"sha256":hash(&b),"original_blob":null}));
 save(&st.join("MANIFIESTO.json"),&json!({"expediente":p["expediente"],"archivos":manifest,"autoria_licencia":p["autoria_licencia"]}))?;println!("CONFORME_DOCUMENTAL: {} archivos preparados; antecedentes preservados.",manifest.len());Ok(())
}
fn publish(st:&Path,repo:&str)->R<()>{
 assert!(["SV-motor","SV-sala-de-maquinas","SV-lenguaje-de-computacion"].contains(&repo));let ep=format!("repos/juantoniolloretegea/{repo}");let prefix=format!("{repo}/");let m:Value=serde_json::from_slice(&fs::read(st.join("MANIFIESTO.json"))?)?;let sel:Vec<_>=m["archivos"].as_array().unwrap().iter().filter(|f|txt(f,"ruta").starts_with(&prefix)).collect();assert!(!sel.is_empty());
 let head=api(&format!("{ep}/git/ref/heads/main"),"GET",None)?;let base=txt(&head["object"],"sha");let mut contents=vec![];
 for f in &sel{let path=txt(f,"ruta").strip_prefix(&prefix).unwrap();match api(&format!("{ep}/contents/{path}?ref={base}"),"GET",None){Ok(v)=>assert_eq!(v["sha"],f["original_blob"],"Contenido concurrente: {path}"),Err(e)=>{assert!(f["original_blob"].is_null()&&e.to_string().contains("HTTP 404"),"No se confirma ausencia o identidad de {path}: {e}");}}let b=fs::read(st.join("revisados-final").join(txt(f,"ruta")))?;assert_eq!(b.len()as u64,f["bytes"].as_u64().unwrap());assert_eq!(hash(&b),txt(f,"sha256"));contents.push(String::from_utf8(b)?);}
 let bc=api(&format!("{ep}/git/commits/{base}"),"GET",None)?;let mut entries=vec![];for(f,s)in sel.iter().zip(&contents){let b=api(&format!("{ep}/git/blobs"),"POST",Some(&json!({"content":s,"encoding":"utf-8"})))?;entries.push(json!({"path":txt(f,"ruta").strip_prefix(&prefix).unwrap(),"mode":"100644","type":"blob","sha":b["sha"]}));}
 let tree=api(&format!("{ep}/git/trees"),"POST",Some(&json!({"base_tree":bc["tree"]["sha"],"tree":entries})))?;let c=api(&format!("{ep}/git/commits"),"POST",Some(&json!({"message":"Documenta CubeCL y alternativa rust-gpu con trazabilidad y límites de recepción","tree":tree["sha"],"parents":[base]})))?;let sha=txt(&c,"sha");save(&st.join(format!("PREPARACION-{repo}.json")),&json!({"repo":repo,"base":base,"commit":sha,"archivos":entries}))?;
 let h=api(&format!("{ep}/git/ref/heads/main"),"GET",None)?;assert_eq!(h["object"]["sha"],base,"Avance concurrente: main intacta");let done=api(&format!("{ep}/git/refs/heads/main"),"PATCH",Some(&json!({"sha":sha,"force":false})))?;assert_eq!(done["object"]["sha"],sha);println!("PUBLICADO {repo} {sha}; cotejo en curso");std::io::stdout().flush()?;
 let mut checked=vec![];for(f,e)in sel.iter().zip(&entries){let path=txt(e,"path");let g=api(&format!("{ep}/contents/{path}?ref={sha}"),"GET",None)?;assert_eq!(g["sha"],e["sha"]);assert_eq!(g["encoding"],"base64");let b=decode(txt(&g,"content"))?;assert_eq!(hash(&b),txt(f,"sha256"));assert_eq!(b.len()as u64,f["bytes"].as_u64().unwrap());assert_eq!(b,fs::read(st.join("revisados-final").join(txt(f,"ruta")))?);checked.push((*f).clone());}
 save(&st.join(format!("COTEJO-{repo}.json")),&json!({"estado":"CONFORME","expediente":"AMD-CALCULO-RUST-20261005","repositorio":repo,"rama":"main","base":base,"commit":sha,"recuperacion":"Contenido completo recuperado desde GitHub por revisión fija; blob vinculado al commit; igualdad de bytes y SHA-256 calculados en Rust","archivos":checked,"autoria_licencia":m["autoria_licencia"]}))?;println!("CONFORME {repo}: {} archivos recuperados en memoria y cotejados.",sel.len());Ok(())
}
fn main()->R<()>{let a:Vec<_>=std::env::args().collect();let st=PathBuf::from(&a[2]).canonicalize()?;assert!(st.starts_with(std::env::current_dir()?.canonicalize()?));match a[1].as_str(){"preparar"=>prepare(&st),"repreparar"=>{let m:Value=serde_json::from_slice(&fs::read(st.join("MANIFIESTO.json"))?)?;for f in m["archivos"].as_array().unwrap(){let p=st.join("revisados-final").join(txt(f,"ruta")).canonicalize()?;assert!(p.starts_with(&st));assert_eq!(hash(&fs::read(&p)?),txt(f,"sha256"));fs::remove_file(p)?;}fs::remove_file(st.join("MANIFIESTO.json"))?;prepare(&st)},"publicar"=>publish(&st,&a[3]),_=>Err("acción no admitida".into())}}
// © 2026 Juan Antonio Lloret Egea. Algunos derechos reservados. | ORCID: 0000-0002-6634-3351 | Instituto Tecnológico Virtual de la Inteligencia Artificial para el Español™ (ITVIA) | IA eñ™ – La Biblia de la IA™ | ISSN 2695-6411 | Licencia Creative Commons Atribución-NoComercial-SinDerivadas 4.0 Internacional (CC BY-NC-ND 4.0).
