use std::{fs,io::Write,path::{Path,PathBuf}};
use serde_json::{Value,json};use sha2::{Digest,Sha256};type R<T>=Result<T,Box<dyn std::error::Error>>;
fn hash(b:&[u8])->String{format!("{:x}",Sha256::digest(b))}
fn text<'a>(v:&'a Value,k:&str)->&'a str{v[k].as_str().unwrap()}
fn read(p:&Path)->R<Value>{Ok(serde_json::from_slice(&fs::read(p)?)?)}
fn save(p:&Path,b:&[u8])->R<()>{fs::create_dir_all(p.parent().unwrap())?;fs::OpenOptions::new().write(true).create_new(true).open(p)?.write_all(b)?;Ok(())}
fn jsonsave(p:&Path,v:&Value)->R<()>{save(p,(serde_json::to_string_pretty(v)?+"\n").as_bytes())}
fn csv(s:&str)->Vec<Vec<String>>{let(mut rows,mut row,mut f,mut q)=(vec![],vec![],String::new(),false);let mut it=s.chars().peekable();while let Some(c)=it.next(){match c{'"'=>{if q&&it.peek()==Some(&'"'){f.push('"');it.next();}else{q=!q;}},',' if !q=>row.push(std::mem::take(&mut f)),'\n' if !q=>{row.push(std::mem::take(&mut f));rows.push(std::mem::take(&mut row));},'\r' if !q=>{},_=>f.push(c)}}assert!(!q);if !f.is_empty()||!row.is_empty(){row.push(f);rows.push(row)}rows}
fn prepare(st:&Path)->R<()>{
 let p=read(&st.join("PLAN.json"))?;let fspec=p["archivos"].as_array().unwrap();assert_eq!(fspec.len(),9);let pie=text(&p,"autoria_licencia");let mut manifest=vec![];
 for f in fspec{let path=text(f,"path");let old=text(f,"original");let new=text(f,"content");assert_ne!(old,new);assert!(!new.contains('\u{fffd}'));assert!(!path.contains("..")&&!path.starts_with('/'));assert!(!path.ends_with("README.md"));
 if path.ends_with(".md"){assert!(new.trim_end().ends_with(pie));}
 if path.ends_with(".json"){let _:Value=serde_json::from_str(new)?;}
 if path.ends_with("HISTORIAL_SUCESOS_SV.csv")||path.ends_with("REGISTRO_EVOLUCION_TECNICA_PROYECTO.csv"){assert!(new.starts_with(old),"Historial alterado: {path}");}
 if path.ends_with("SUCESOS_SV.md"){let a=old.find("## S39").unwrap();let b=old.find("## S40").unwrap();assert!(new.starts_with(&old[..a])&&new.ends_with(&old[b..]));}
 if path.ends_with("ACTA_004_FINALIDAD_ALCANCE_Y_CONTINUIDAD_EIO_2026_09_22.md")||path.ends_with("REGISTRO_EVOLUCION_TECNICA_PROYECTO.md"){let k=old.rfind(pie).unwrap();assert!(new.starts_with(&old[..k])&&new.ends_with(&old[k..]));}
 if path.ends_with("/SUCESOS_SV.csv")||path.ends_with("TIQUES_TECNICOS.csv"){let a=csv(old);let b=csv(new);assert_eq!(a.len(),b.len());for(x,y)in a.iter().zip(&b){let target=if path.ends_with("TIQUES_TECNICOS.csv"){x.get(1).map(String::as_str)==Some("TT-0020")}else{x[0]=="S39"};if !target{assert_eq!(x,y,"Fila ajena alterada");}}}
 let bytes=new.as_bytes();save(&st.join("preparados").join(path),bytes)?;manifest.push(json!({"path":path,"bytes":bytes.len(),"sha256":hash(bytes),"original_blob":f["original_blob"]}));
 }
 let get=|suffix:&str|->&str{text(fspec.iter().find(|f|text(f,"path").ends_with(suffix)).unwrap(),"content")};
 let s=csv(get("/SUCESOS_SV.csv"));let h=csv(get("HISTORIAL_SUCESOS_SV.csv"));let sr=s.iter().find(|r|r[0]=="S39").unwrap();assert_eq!(h.last().unwrap()[0],"40");assert_eq!(&h.last().unwrap()[1..],sr.as_slice());assert_eq!(sr[1],"en ejecución");
 let oldh=csv(text(fspec.iter().find(|f|text(f,"path").ends_with("HISTORIAL_SUCESOS_SV.csv")).unwrap(),"original"));assert_eq!(oldh.last().unwrap()[0],"39");assert_eq!(h.len(),oldh.len()+1);
 let t=csv(get("TIQUES_TECNICOS.csv"));let tt=t.iter().find(|r|r.get(1).map(String::as_str)==Some("TT-0020")).unwrap();assert_eq!(tt[3],"en ejecución");
 let tj:Value=serde_json::from_str(get("TT-0020_CALCULO_RUST_AMD_2026-10-05.json"))?;assert_eq!(tj["revision_suceso"],40);assert_eq!(tj["estado"],tt[3]);assert_eq!(tj["resultado_actual"],tt[8]);assert_eq!(tj["fecha_actualizacion_utc"],tt[5]);assert_eq!(tj["fecha_fin_utc"],Value::Null);assert_eq!(tj["recepcion_finalizada"],false);assert_eq!(tj["inferencia_acreditada"],false);assert_eq!(tj["modelo_instalado"],false);assert_eq!(tj["estudio_en_curso"]["nuevos_recursos_autorizados"],false);
 assert!(get("ACTA_004_FINALIDAD_ALCANCE_Y_CONTINUIDAD_EIO_2026_09_22.md").contains("## 34."));let ret=csv(get("REGISTRO_EVOLUCION_TECNICA_PROYECTO.csv"));assert_eq!(ret.last().unwrap()[0],"RETP-2026-279");assert_eq!(ret.iter().filter(|r|r[0]=="RETP-2026-279").count(),1);
 let dir="docs/calidad/tuberias-ia/continuacion-15-09-2026/";let src=fs::read(st.join("CONTROL.rs"))?;let sp=format!("{dir}CONTROL_RECEPCION_AMD_ENCARGO_ZAI_20261006.rs");save(&st.join("preparados").join(&sp),&src)?;manifest.push(json!({"path":sp,"bytes":src.len(),"sha256":hash(&src),"original_blob":null}));
 let check=json!({"estado":"CONFORME_DOCUMENTAL","expediente":p["expediente"],"fecha":p["fecha"],"base":p["base"],"comprobaciones":["S39 revisión 40 CSV e historial concordantes","Antecedentes íntegros y otras filas intactas","TT-0020 en ejecución, recepción integral y modelo pendientes","Acta 004 sección 34 y RETP-2026-279","UTF-8, JSON, tamaños y SHA-256 Rust"],"alcance":"Concordancia del seguimiento; no nueva ejecución GPU o del modelo","archivos":manifest,"autoria_licencia":pie});let cb=(serde_json::to_string_pretty(&check)?+"\n").into_bytes();let cp=format!("{dir}CONTROL_RECEPCION_AMD_ENCARGO_ZAI_20261006.json");save(&st.join("preparados").join(&cp),&cb)?;manifest.push(json!({"path":cp,"bytes":cb.len(),"sha256":hash(&cb),"original_blob":null}));
 jsonsave(&st.join("MANIFIESTO.json"),&json!({"expediente":p["expediente"],"base":p["base"],"archivos":manifest,"autoria_licencia":pie}))?;println!("CONFORME_DOCUMENTAL: {} archivos; S39 r40, TT-0020, Acta 004 §34 y RETP-279",manifest.len());Ok(())
}
fn verify(st:&Path)->R<()>{let m=read(&st.join("MANIFIESTO.json"))?;let r=read(&st.join("RECUPERADOS.json"))?;let files=m["archivos"].as_array().unwrap();assert_eq!(files.len(),r["archivos"].as_array().unwrap().len());for f in files{let path=text(f,"path");let b=fs::read(st.join("preparados").join(path))?;let got=r["archivos"].as_array().unwrap().iter().find(|g|text(g,"path")==path).unwrap();let remote=text(got,"content").as_bytes();assert_eq!(b,remote,"Bytes discordantes: {path}");assert_eq!(hash(remote),text(f,"sha256"));assert_eq!(remote.len()as u64,f["bytes"].as_u64().unwrap());}
 jsonsave(&st.join("COTEJO-PUBLICACION.json"),&json!({"estado":"CONFORME","repositorio":"juantoniolloretegea/SV-lenguaje-de-computacion","rama":"main","commit":r["commit"],"base":m["base"],"recuperacion":"Contenido completo de once archivos por revisión fija, cotejado por bytes y SHA-256 en Rust","archivos":m["archivos"],"autoria_licencia":m["autoria_licencia"]}))?;println!("CONFORME_CUSTODIA: {} archivos",files.len());Ok(())}
fn clean(st:&Path)->R<()>{let m=read(&st.join("MANIFIESTO.json"))?;let c=read(&st.join("COTEJO-PUBLICACION.json"))?;assert_eq!(c["estado"],"CONFORME");assert_eq!(c["archivos"],m["archivos"]);let mut paths=vec![];for f in m["archivos"].as_array().unwrap(){let p=st.join("preparados").join(text(f,"path")).canonicalize()?;assert!(p.starts_with(st));let b=fs::read(&p)?;assert_eq!(hash(&b),text(f,"sha256"));paths.push(p);}for n in ["PLAN.json","RECUPERADOS.json"]{let p=st.join(n).canonicalize()?;assert!(p.starts_with(st));paths.push(p);}let mut rows=vec![];let mut total=0;for p in paths{let b=fs::read(&p)?;rows.push(json!({"ruta":p.strip_prefix(st)?.to_string_lossy(),"bytes":b.len(),"sha256":hash(&b)}));total+=b.len();fs::remove_file(&p)?;}jsonsave(&st.join("RETIRADA-LOCAL.json"),&json!({"archivos":rows,"bytes_logicos":total,"motivo":"Duplicados cotejados y ensamblados regenerables; fuentes y constancias conservadas"}))?;println!("RETIRADA_CONFORME: {total} bytes lógicos");Ok(())}
fn main()->R<()>{let a:Vec<_>=std::env::args().collect();assert_eq!(a.len(),3);let st=PathBuf::from(&a[2]).canonicalize()?;assert!(st.starts_with(std::env::current_dir()?.canonicalize()?));match a[1].as_str(){"preparar"=>prepare(&st),"cotejar"=>verify(&st),"retirar"=>clean(&st),_=>Err("acción".into())}}
// © 2026 Juan Antonio Lloret Egea. Algunos derechos reservados. | ORCID: 0000-0002-6634-3351 | Instituto Tecnológico Virtual de la Inteligencia Artificial para el Español™ (ITVIA) | IA eñ™ – La Biblia de la IA™ | ISSN 2695-6411 | Licencia Creative Commons Atribución-NoComercial-SinDerivadas 4.0 Internacional (CC BY-NC-ND 4.0).
