from pathlib import Path
import json,hashlib,copy
R=Path('manifiesto-sv/checkout');B=R/'docs/calidad/tuberias-ia/paridad-imagen-celula-matematica/estudio-nucleo-agentes';D=B/'bis03-sedes-i0205-v0_1';D.mkdir();(D/'activos').mkdir();(D/'soporte').mkdir()
def H(b):return hashlib.sha256(b).hexdigest()
def write(p,x):(D/p).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
base='3c4f5f87e2e052daacb25be4a4dfe7c1db0d946d';lab='e1779bdfc53ab815e7b3dc2c24914c3ecdafc3a2'
prior=json.loads((B/'integracion-c02-c05-v0_1/FUENTES.json').read_text())['rectores_y_contratos'];sources={p:{'sha256':H((R/p).read_bytes()),'lectura':'completa previa revalidada por identidad'} for p in prior}
for p,scope in [('rust/Cargo.toml','completa'),('rust/Cargo.lock','completa'),('rust/sv_core/Cargo.toml','completa'),('rust/sv_core/src/lib.rs','completa'),('rust/sv_core/src/ir.rs','tipos y accesores públicos, líneas 1–215'),('rust/sv_core/src/nat.rs','completa'),('rust/sv_core/src/frontend.rs','SourceProfile; constitución CellSpec y square_nat; no lectura completa del parser'),('rust/sv_core/src/wellformed.rs','CellSpec, CellState, CoupledState; no lectura completa'),('rust/sv_core/src/bindings.rs','tipos y validación LIG, líneas 1–330; no lectura completa'),('rust/sv_native/src/main.rs','completa'),('docs/calidad/tuberias-ia/ie004/recepcion-av/json_estricto.rs','completa'),('docs/calidad/tuberias-ia/ie004/recepcion-av/sha256.rs','completa')]:sources[p]={'sha256':H((R/p).read_bytes()),'lectura':scope}
for name in ['CONTRATO_INTEGRADO.md','BANCO_PREVIO.json','ORACULOS.json','PRESUPUESTO.json','MANIFIESTO.json']:
 p=str((B/'integracion-c02-c05-v0_1'/name).relative_to(R));sources[p]={'sha256':H((R/p).read_bytes()),'lectura':'compromiso RETP-218 íntegro conservado; consulta aplicable en este incremento'}
write('FUENTES.json',{'corte_publico':base,'corte_laboratorio':lab,'archivos':sources})
seats=[
 ('SE01',['BIS-O01','BIS-O05','BIS-O11'],'ya preservada en alcance existente','sv_core::compile_svp_profile; SourceProfile::from_tag; IrProgram','Usar entrada pública con perfil explícito y consumir exclusivamente IR aceptada.','I0205-01 / I0205-21 / I0205-22'),
 ('SE02',['BIS-O02','BIS-O05'],'falta comprobación integrada','crate experimental sv_bis_i0205 / soporte','Recorrer todas las CellSpec y comparar Nat decimal con perfil exacto; convertir a tamaño de máquina sólo tras admisión.','I0205-04 / I0205-05 / I0205-06'),
 ('SE03',['BIS-O03','BIS-O04'],'falta comprobación integrada','crate experimental sv_bis_i0205 / identidad','Resolver arquitectura → nodo CoupledSpec → CellSpec y CoupledState; agregar vínculo externo de instancia/revisión. No insertar campos nuevos en IR.','I0205-01 / I0205-02 / I0205-03 / I0205-07 / I0205-08 / I0205-23 / I0205-24'),
 ('SE04',['BIS-O01','BIS-O02','BIS-O07'],'falta encapsulación en el montaje','crate experimental sv_bis_i0205 / estado','Enum privado de arrays 16/25/49 tras soporte; lectura por slice, sin setters ni crecimiento. No sustituir los Vec de la IR.','I0205-01 / I0205-24; puerta de construcción/encapsulación en INTERFAZ.md'),
 ('SE05',['BIS-O01','BIS-O04'],'responsabilidad de representación derivada','crate experimental sv_bis_i0205 / geometria','Comprobar descriptor exacto frente a estado y convenio; contrastar SHA esperado después de matemática.','I0205-01 / I0205-09 / I0205-10 / I0205-11'),
 ('SE06',['BIS-O04','BIS-O08'],'responsabilidad externa instrumentada','receptor local y captor del laboratorio; observador separado del sujeto','Captura final del buffer; recibo y veredicto se contrastan con contexto independiente. No lectura de oráculos por el sujeto.','I0205-01 / I0205-12 / I0205-13 / I0205-14 / I0205-15 / I0205-16 / I0205-25 / I0205-26'),
 ('SE07',['BIS-O07','BIS-O09'],'responsabilidad de frontera y estado técnico','sv_bis_i0205 / recepcion y conductor','Nota documental sin intérprete; operación fijada fuera de petición; rechazo/ausencia/fallo distintos de Tri.U.','I0205-17 / I0205-18 / I0205-25'),
 ('SE08',['BIS-O10'],'falta comprobación y medición de recursos','adaptador de recepción y observación de proceso','Cuotas de bytes del compromiso y complemento estructural; RAM y duración siguen pendientes.','I0205-19 / I0205-20; banco de adaptador'),
 ('SE09',['BIS-O11'],'ya preservada parcialmente; extensión pendiente','SourceProfile existente + documentación ES/EN del crate experimental','Mantener separación entre perfil fuente, idioma del comentario e interfaz. Integración en explícito; paridad integrada ES pendiente.','I0205-01 / I0205-21; C12 propio pendiente'),
 ('SE10',['BIS-O12'],'responsabilidad transversal de conductor y observador','expediente por ejecución / capturas / observador','Guardar bytes fuente, scripts y parches, versiones, entradas, salidas y primera guarda; no acreditar a partir del plan de inyección.','OBS-01–OBS-04 del banco integrado'),
 ('SE11',['BIS-O06'],'exclusión expresa de esta realización','Frame, composición, Trayectoria y consulta conservan sus sedes y contratos','No realizar una nueva operación de composición, evaluación o consulta por presentar un descriptor.','C06 / C07 y resto del workflow pendientes'),
 ('SE12',['BIS-O03','BIS-O09'],'existente distinto del enlace propuesto','sv_core::bindings::validate_bindings / LIG/0.1','Conservar ligaduras existentes. El fixture carece de Domain/Agent/BindingContract constituidos; no introducirlos para simular esa cobertura.','C03 original; DFL-005 no cerrada por esta ruta')]
write('DECISION_SEDES.json',{'version':'BIS-03-I0205-SEDES/0.1','estado':'DECISION_ACOTADA_DOCUMENTADA','alcance':'Montaje experimental del banco integrado C02–C05; sin promoción productiva ni ampliación de semántica o IR.','corte':base,'sede_fisica':'Workspace de laboratorio aislado, crate sv_bis_i0205 dependiente por ruta de copia verificada de sv_core al corte de entrada.','dependencias_nuevas_de_registro':[],'cambios_en_workspace_productivo':False,'decisiones':[dict(id=id,obligaciones=ob,clasificacion=cl,sede=se,decision=de,casos=ca) for id,ob,cl,se,de,ca in seats]})
write('LIMITES_ADAPTADOR.json',{'version':'BIS-I0205-JSON/0.1','estatuto':'Complemento experimental previo del adaptador, no límite semántico SV ni cota de RAM de proceso. No reescribe PRESUPUESTO RETP-218.','max_bytes_decodificacion':8192,'max_contenedores_anidados':32,'max_nodos':512,'max_miembros_por_objeto':32,'conteo_nodos':'Una unidad por valor JSON, incluidos arrays y objetos; las claves no son nodos adicionales.','conteo_profundidad':'Sólo contenedores abiertos simultáneamente; escalar raíz=0.','numeros':'Lexema decimal entero exacto, con signo negativo salvo -0. Sin fracción ni exponente en este subconjunto. No conversión global a u64/f64.','prioridad':'Cuota de bytes antes de UTF-8/JSON; profundidad antes de entrar al contenedor; nodos antes de añadir valor; duplicados tras decodificar clave; miembros antes de almacenar el siguiente par.','conservacion':'Mantener bytes originales para hashes y entrega; decodificación de escapes no autoriza normalizar el artefacto.'})
cases=[]
def add(id,kind,body,expected):
 p='activos/'+id+'.bin';(D/p).write_bytes(body);cases.append({'id':id,'tipo':kind,'entrada':{'archivo':p,'bytes':len(body),'sha256':H(body)},'esperado':expected,'observado':None,'estado':'PENDIENTE'})
add('J01','json','{"s":"ñ 😀","t":"\\u00f1"}'.encode(),{'resultado':'ADMISIBLE_DECODIFICADOR','valores_texto':{'s':'ñ 😀','t':'ñ'}})
add('J02','json',b'-1',{'resultado':'ADMISIBLE_DECODIFICADOR','lexema_numero':'-1'})
add('J03','json',b'18446744073709551616',{'resultado':'ADMISIBLE_DECODIFICADOR','lexema_numero':'18446744073709551616','nota':'El tipado de un campo u64 deberá rechazarlo después; no truncar.'})
add('J04','json',b'{"a":0,"\\u0061":1}',{'resultado':'RECHAZADO','causa':'CLAVE_DUPLICADA'})
add('J05','json',b'"\xff"',{'resultado':'RECHAZADO','causa':'UTF8'})
add('J06','json',b'{}{}',{'resultado':'RECHAZADO','causa':'JSON_SINTAXIS'})
for id,d,ok in [('J07',32,True),('J08',33,False)]:add(id,'json',b'['*d+b'0'+b']'*d,{'resultado':'ADMISIBLE_DECODIFICADOR' if ok else 'RECHAZADO',**({'contenedores_anidados':d} if ok else {'causa':'PROFUNDIDAD'})})
for id,n,ok in [('J09',511,True),('J10',512,False)]:add(id,'json',('['+','.join(['0']*n)+']').encode(),{'resultado':'ADMISIBLE_DECODIFICADOR' if ok else 'RECHAZADO',**({'nodos':n+1} if ok else {'causa':'NODOS'})})
for id,n,ok in [('J11',32,True),('J12',33,False)]:add(id,'json',json.dumps({f'k{i}':0 for i in range(n)},separators=(',',':')).encode(),{'resultado':'ADMISIBLE_DECODIFICADOR' if ok else 'RECHAZADO',**({'miembros':n} if ok else {'causa':'MIEMBROS'})})
for id,b in [('J13',b'1.0'),('J14',b'-0')]:add(id,'json',b,{'resultado':'RECHAZADO','causa':'NUMERO_FORMA'})
for id,b in [('H01',b''),('H02',b'abc'),('H03',bytes(range(55))),('H04',bytes(range(56))),('H05',bytes(range(64)))]:add(id,'sha256',b,{'resultado':'HUELLA_EXACTA','sha256':H(b)})
write('BANCO_ADAPTADOR_PREVIO.json',{'version':'BIS-03-I0205-ADAPTADOR/0.1','estatuto':'Casos instrumentales independientes, previos a adaptar el código. No reemplazan los 26 integrados ni los 202 anteriores.','casos':cases,'json_preparados':14,'sha256_preparados':5,'ejecutados_rust':0,'oraculo_hash':'hashlib.sha256 de Python como referencia instrumental independiente; no interpreta SVP.'})
print(D)
