from pathlib import Path
import sys,json
sys.path.insert(0,'bis-c02');import registro as r
D=r.B/'bis03-sedes-i0205-v0_1';t=r.now();fields,rs=r.rows();row=next(x for x in rs if x['id']=='S22');assert row['estado']=='en ejecución'
row.update(fecha_actualizacion_utc=t,cortes_de_entrada='Lenguaje 3c4f5f87e2e052daacb25be4a4dfe7c1db0d946d; laboratorio e1779bdfc53ab815e7b3dc2c24914c3ecdafc3a2',resultado='Decisión acotada de sedes C02–C05: composición experimental en Rust alrededor de compile_svp_profile, sin cambios de semántica/IR ni workspace productivo. Interfaz de recepción/estado/descriptor y observador separada; doce decisiones cartografían doce obligaciones. Se comprometen 14 casos instrumentales JSON y 5 SHA, sin ejecutar. Los 26 casos integrados de RETP-218 permanecen intactos.',verificacion='Lectura estática de API pública, IR, Nat, ligaduras y auxiliares previos con huellas y alcance de lectura. Compatibilidad estructural de los 26 casos frente al complemento del adaptador; límites positivos/negativos literales, hashes y observados vacíos comprobados documentalmente. Cero ejecuciones nuevas Rust. Historial y RETP append-only; otros sucesos intactos.',evidencias='https://github.com/juantoniolloretegea/SV-lenguaje-de-computacion/blob/main/'+str(D.relative_to(r.R))+'/README.md',referencia_calidad='https://github.com/juantoniolloretegea/SV-lenguaje-de-computacion/blob/main/docs/calidad/REGISTRO_EVOLUCION_TECNICA_PROYECTO.md#retp-219',siguiente_accion='Materializar en laboratorio el crate sv_bis_i0205 y su conductor/observador conforme a la decisión, fijar las sondas de construcción antes de ejecutarlas, compilar y ensayar auxiliares y recorrido C02–C05 en Rust con resultados separados de expectativas.',observaciones='BIS-03 en ejecución acotada: sedes del primer montaje documentadas; BIS-02 global sigue abierto y BIS-04 queda pendiente de realización. No promoción productiva, cierre de DFL-005 ni catálogo. Perfiles ES/EN integrados, imagen/consumo visual, RAM y tiempo de proceso pendientes. S24/GUI diferida; S25 instrumental conservado.')
r.guardar(fields,rs,row);r.retp(219,'S22 · Decisión de sedes y recepción del montaje C02–C05',t,row,str(D.relative_to(r.R/'docs/calidad'))+'/README.md','DECISION_ACOTADA_DE_SEDES','Workflow V2; rectores revalidados; RETP-218; API pública Rust y auxiliares documentales inspeccionados','Sedes e interfaz experimental fijadas; realización y ejecución Rust pendientes')
p=r.B/'ESTADO_WORKFLOW.json';s=json.loads(p.read_text());s.update(ultimo_retp='RETP-2026-219',ultimo_informe='bis03-sedes-i0205-v0_1/README.md',siguiente_accion=row['siguiente_accion'])
for e in s['etapas']:
 if e['id']=='BIS-03':e.update(estado='en ejecución',alcance='Decisión de sedes del primer montaje C02–C05 documentada; resto de obligaciones y sedes fuera del montaje pendientes. No cierre global de BIS-02.')
s['integracion_c02_c05']['apertura_formal_bis03']=True
s['integracion_c02_c05']['registro_paso_acotado_bis03']='RETP-2026-219'
s['decision_sedes_i0205']={'estado':'finalizada en alcance documental del montaje','informe':'bis03-sedes-i0205-v0_1/DECISION.md','interfaz':'bis03-sedes-i0205-v0_1/INTERFAZ.md','banco_complementario':'bis03-sedes-i0205-v0_1/BANCO_ADAPTADOR_PREVIO.json','paso_acotado_a_bis03':True,'cierre_global_bis02':False,'ampliacion_semantica_ir':False,'casos_instrumentales_preparados':19,'casos_instrumentales_ejecutados':0,'realizacion_rust':'pendiente'}
p.write_text(json.dumps(s,ensure_ascii=False,indent=2)+'\n')
p=r.L;s=p.read_text().replace('**Trabajo vigente: S22 / RETP-2026-218.','**Trabajo vigente: S22 / RETP-2026-219.');start=s.index('**Siguiente objeto material:**');end=s.index('\n\n',start)
s=s[:start]+'''**Siguiente objeto material:** materializar y ensayar en Rust el [montaje C02–C05 con sedes e interfaz fijadas](../paridad-imagen-celula-matematica/estudio-nucleo-agentes/bis03-sedes-i0205-v0_1/README.md), RETP-219. Se elige un crate experimental separado sobre la API pública de sv_core, sin ampliar semántica/IR. Los [26 casos integrados de RETP-218](../paridad-imagen-celula-matematica/estudio-nucleo-agentes/integracion-c02-c05-v0_1/README.md) permanecen intactos y sin ejecutar; se añaden 19 casos instrumentales previos para adaptar JSON y SHA. BIS-03 en ejecución acotada; BIS-02 global abierto y BIS-04 pendiente. Se conservan los conteos originales (2 ejecutados, 22 pendientes), las 202 filas previas C02–C12 sin ejecutar y las 13 variantes históricas C01. Rust/Cargo 1.98.0 recuperados en S25; S24 conserva la GUI diferida.''' +s[end:];p.write_text(s)
print(t)
