from pathlib import Path
R=Path(__file__).resolve().parent
s=(R.parent/'s16-fronteras/registrar.py').read_text()
s=s.replace("P=R.parent/'s15-causas/actualizacion-cierre'","P=R.parent/'s16-fronteras/actualizacion'")
s=s.replace('s16-fronteras-pendientes','s17-contrato-recorrido-conjunto').replace('ACTA_FRONTERAS.md','ACTA_CONTRATO_S17.md').replace('range(16)','range(17)').replace("id='S16'","id='S17'").replace('retp-187','retp-188').replace('RETP-187','RETP-188').replace('RETP-2026-187','RETP-2026-188')
a=s.index("row={k:'' for k in fields}");b=s.index('\nrows.append(row)',a)
s=s[:a]+'''row={k:'' for k in fields};row.update(id='S17',estado='finalizado',fecha_alta_utc=T,fecha_inicio_utc=start,fecha_actualizacion_utc=T,fecha_fin_utc=T,unidad_responsable='Watson / W-S0',actividad='Contrato del recorrido documental conjunto: contexto, base, recepción, cobertura y entrega',alcance='Contrato candidato S17 y banco de 24 obligaciones. Adaptación explícita de interfaces; sin implementación ni ejecución conjunta.',repositorios_y_ramas='SV-lenguaje-de-computacion: main; SV-matematica-semantica-cuaternaria: lab/playground-sv-permanente',cortes_de_entrada='Lenguaje '+cut['cortes']['lenguaje']['head']+'; laboratorio '+cut['cortes']['laboratorio']['head'],dependencias='S16 / RETP-187; S11/S14/S15; cápsula original G1/S2; rectores y relevo S12/S13.',resultado='Contrato y obligaciones fijados. Enlace directo insuficiente: lote fijo S2, Vista S14 y bytes de Informe S15 no equivalen a una entrega tipada. Adaptación y conformidad ejecutable pendientes.',verificacion='15 fuentes íntegras, cuatro interfaces encapsuladas y 11 pasajes exactos; 24 casos fijados; cero ensayos funcionales nuevos. Esperados originales S14 intactos.',evidencias=url,referencia_calidad=pub+'/blob/main/docs/calidad/REGISTRO_EVOLUCION_TECNICA_PROYECTO.md#retp-188',siguiente_accion=cut['siguiente_objeto'],observaciones='S17 cierra un contrato documental, no una campaña. 144 observaciones normales previstas, ninguna realizada. Presupuesto e implementación por fijar antes de ejecutar. B/E/K/L y puertas P3/P4/P5/P6 vigentes; sin promoción nuclear; agentes por decidir tras inmunología.')''' + s[b:]
a=s.index("entry=f'");b=s.index("readme=(P/",a)
s=s[:a]+'''entry=f'\\n\\n<a id="retp-188"></a>\\n\\n### RETP-2026-188 · S17 · Contrato del recorrido documental conjunto\\n\\n{T}. [Acta y contrato]({wp}/ACTA_CONTRATO_S17.md). {row["resultado"]} {row["verificacion"]} Se fija la relación entre producción G1, base consumida, contexto, recepción completa y entrega tipada; no se cambia el lote anterior ni se eleva una lista de bytes a credencial. **Siguiente objeto único:** {row["siguiente_accion"]} {row["observaciones"]}\\n'
(O/'registro.md').write_bytes((P/'registro.md').read_bytes()+entry.encode());s=io.StringIO(newline='');csv.writer(s,lineterminator='\\n').writerow(['RETP-2026-188',T[:10],'','CONTRATO_DOCUMENTAL','S17 / contrato integración 1+3','Contexto, base, recepción, cobertura y entrega tipada','Luz verde tras S16 / RETP-187','S11; S14; S15; S16; interfaces G1/S2; rectores','Contrato, banco, diagnósticos, fuentes, pasajes, comprobador, Sucesos y espejo',row['verificacion'],row['resultado'],'Sin promoción nuclear; ninguna ejecución integrada acreditada',row['siguiente_accion'],'finalizado']);(O/'registro.csv').write_bytes((P/'registro.csv').read_bytes()+s.getvalue().encode())
''' + s[b:]
s=s.replace('## S16 · Fronteras pendientes · RETP-188','## S17 · Contrato del recorrido conjunto · RETP-188').replace('S16 / RETP-188 preparado; S0–S15 e históricos íntegros.','S17 / RETP-188 preparado; S0–S16 e históricos íntegros.')
(R/'registrar.py').write_text(s)
s=(R.parent/'s16-fronteras/publicar.py').read_text().replace('calidad: registrar fronteras pendientes y fases de fallo; S16 / RETP-187','calidad: fijar contrato del recorrido documental conjunto; S17 / RETP-188');(R/'publicar.py').write_text(s)
