from pathlib import Path
import sys,json
sys.path.insert(0,'bis-c02');import registro as r
D=r.B/'bis04-realizacion-i0205-v0_1';t=r.now();fields,rs=r.rows();row=next(x for x in rs if x['id']=='S22');assert row['estado']=='en ejecución'
row.update(fecha_actualizacion_utc=t,cortes_de_entrada='Lenguaje 2067310b30e5aee76120444f0166b01390a04970; laboratorio 4705ba49c917cb525eeeba4b39f16686afe1e255',resultado='Montaje experimental sv_bis_i0205 implementado y ensayado en Rust/Cargo 1.98.0 con copia verificada de sv_core. 26 casos integrados conformes: 7 entregas documentales concordantes, 17 rechazos y 2 no acreditados. 19 instrumentales conformes, secuencia v1→v2→v1 y 4 sensibilidades del observador conformes. Ocho sondas externas verifican privacidad/API; almacenamiento y lectura agregada probados. Primera campaña conservada; revisión R01 acota recepción al saldo antes de reservar/leer y se comprueba en segunda campaña.',verificacion='Fuentes/sondas fijadas en laboratorio y espejo antes de ejecutar; cargo build/test --locked --offline, rustc y binario nativo. Dos campañas, cada una con 26 casos, 3 repeticiones y 1 lectura adicional: 60 invocaciones totales, 26 variantes integradas únicas. Ocho sondas externas por campaña; segunda campaña añade prueba R01 con 6145 bytes leídos frente a saldo 6144. Diagnósticos, capturas, estados, códigos de salida, huellas y recursos conservados. Cero modificaciones de oráculos previos, fuentes productivas o estados de otros sucesos.',evidencias='https://github.com/juantoniolloretegea/SV-lenguaje-de-computacion/blob/main/'+str(D.relative_to(r.R))+'/README.md',referencia_calidad='https://github.com/juantoniolloretegea/SV-lenguaje-de-computacion/blob/main/docs/calidad/REGISTRO_EVOLUCION_TECNICA_PROYECTO.md#retp-220',siguiente_accion='Preparar la extensión del montaje a paridad ES/EN integrada y controles de recursos/captura pendientes mediante banco previo; conservar abierta la suficiencia global y la secuencia Bis → catálogo/cierre de fase → GUI.',observaciones='BIS-04 en ejecución acotada; BIS-02/BIS-03 globales abiertos. Los 202 casos originales C02–C12 siguen sin ejecutar; no se recuentan como integrados. Entrega documental local; sin consumo visual de IA, constitución operativa ni promoción productiva. RAM/tiempo observados sin límites constituidos; agotamiento y todas las cuotas de salida pendientes. S24/GUI diferida y S25 conservados.')
r.guardar(fields,rs,row);r.retp(220,'S22 · Realización y campaña nativa integrada C02–C05',t,row,str(D.relative_to(r.R/'docs/calidad'))+'/README.md','REALIZACION_EXPERIMENTAL_Y_VERIFICACION_NATIVA','Workflow V2; RETP-218 y 219; bancos y sondas comprometidos antes de ejecutar','Primer recorrido C02–C05 acreditado en su alcance de laboratorio; fase global abierta')
p=r.B/'ESTADO_WORKFLOW.json';s=json.loads(p.read_text());s.update(ultimo_retp='RETP-2026-220',ultimo_informe='bis04-realizacion-i0205-v0_1/README.md',siguiente_accion=row['siguiente_accion'])
for e in s['etapas']:
 if e['id']=='BIS-04':e.update(estado='en ejecución',alcance='Realización experimental C02–C05 y 26 casos integrados ejecutados; no cierre global del workflow ni promoción productiva.')
s['integracion_c02_c05'].update(estado='realización Rust y campaña conformes en alcance local documental',casos_ejecutados=26,sensibilidades_ejecutadas=4,resultado='7 concordantes, 17 rechazados, 2 no acreditados',campanas=2,invocaciones_totales=60,realizacion='bis04-realizacion-i0205-v0_1/README.md')
s['decision_sedes_i0205'].update(casos_instrumentales_ejecutados=19,realizacion_rust='implementada y ensayada; RETP-2026-220')
s['realizacion_bis04_i0205']={'registro':'RETP-2026-220','campanas':2,'integrados_unicos':26,'invocaciones_por_campana':30,'instrumentales_unicos':19,'sensibilidades_unicas':4,'sondas_externas_unicas':8,'tests_internos_segunda_campana':2,'oraculos_previos_modificados':False,'suficiencia_global':False}
p.write_text(json.dumps(s,ensure_ascii=False,indent=2)+'\n')
p=r.L;text=p.read_text().replace('**Trabajo vigente: S22 / RETP-2026-219.','**Trabajo vigente: S22 / RETP-2026-220.');a=text.index('**Siguiente objeto material:**');b=text.index('\n\n',a)
text=text[:a]+'''**Siguiente objeto material:** extender el [montaje nativo C02–C05 verificado](../paridad-imagen-celula-matematica/estudio-nucleo-agentes/bis04-realizacion-i0205-v0_1/README.md), RETP-220, a paridad ES/EN integrada y a controles pendientes mediante banco previo. El crate Rust compila offline y ejecuta 26 casos integrados, 19 instrumentales, la secuencia v1→v2→v1 y cuatro sensibilidades del observador. Sondas externas e internas acreditan encapsulación y lectura acotada; dos campañas preservadas, sin cambiar esperados. BIS-04 en ejecución acotada; BIS-02/BIS-03 globales abiertos. Las 202 filas originales C02–C12, los 24 escenarios originales (2 ejecutados, 22 pendientes) y las 13 variantes C01 conservan su identidad y contabilidad. S24/GUI diferida; S25 instrumental conservado.''' +text[b:];p.write_text(text)
print(t)
