from pathlib import Path
import sys,json,subprocess,hashlib,shutil
sys.path.insert(0,'bis-c02');import registro as r
D=r.B/'integracion-c02-c05-v0_1';t=r.now();fields,rs=r.rows();row=next(x for x in rs if x['id']=='S22');assert row['estado']=='en ejecución'
row.update(fecha_actualizacion_utc=t,cortes_de_entrada='Lenguaje 18963fa275d2a29633e164d9a2ea5fe1c4f11216; laboratorio 3678ae6c2881d74b2d46da99c33775d6a2979108',resultado='Compromiso documental del recorrido integrado C02–C05: 26 casos, 7 positivos y 19 negativos, contextos confiables separados, oráculos y estímulos de captura literales. Cero ejecuciones nuevas de integración. C01 conserva 13 variantes históricas; C02–C12 conservan 202 filas previas sin ejecutar.',verificacion='Verificador administrativo: referencias, SHA256, longitudes, IDs, observados vacíos, fórmulas geométricas contra estado independiente, deltas discriminantes y cuotas literales conformes. No compila SVP ni ejecuta receptor Rust. Rust/Cargo 1.98.0 siguen disponibles tras S25. Historial y RETP se amplían sin sobrescribir entradas previas.',evidencias='https://github.com/juantoniolloretegea/SV-lenguaje-de-computacion/blob/main/'+str(D.relative_to(r.R))+'/README.md',referencia_calidad='https://github.com/juantoniolloretegea/SV-lenguaje-de-computacion/blob/main/docs/calidad/REGISTRO_EVOLUCION_TECNICA_PROYECTO.md#retp-218',siguiente_accion='Resolver las sedes e interfaz de recepción/observación del recorrido C02–C05 para BIS-03 y documentar las condiciones de paso aplicables; después realizar y ensayar en Rust contra el banco comprometido.',observaciones='BIS-02 sigue abierto; BIS-03 no se abre formalmente en este incremento. Soporte y presupuesto sintéticos; RAM, duración, paridad ES/EN integrada e imagen/consumo visual pendientes. Los siete positivos son expectativas, no siete pruebas superadas. S24 mantiene Bis → catálogo y cierre de fase → análisis e instalación de GUI. S25 conserva su cierre instrumental.')
r.guardar(fields,rs,row)
r.retp(218,'S22 · Compromiso del recorrido documental integrado C02–C05',t,row,str(D.relative_to(r.R/'docs/calidad'))+'/README.md','CONTRATO_Y_BANCO_PREVIO','Workflow V2; contratos C02–C05 y guardas C08–C12; consolidación RETP-216; recuperación S25/RETP-217','Contrato común y datos previos fijados; realización Rust pendiente')
p=r.B/'ESTADO_WORKFLOW.json';s=json.loads(p.read_text());s.update(siguiente_accion=row['siguiente_accion'],ultimo_informe='integracion-c02-c05-v0_1/README.md',ultimo_retp='RETP-2026-218');s['integracion_c02_c05']={'contrato':'integracion-c02-c05-v0_1/CONTRATO_INTEGRADO.md','banco':'integracion-c02-c05-v0_1/BANCO_PREVIO.json','estado':'compromiso documental previo; realización pendiente','casos_preparados':26,'positivos_previstos':7,'negativos_previstos':19,'casos_ejecutados':0,'sensibilidades_previstas':4,'sensibilidades_ejecutadas':0,'cierre_bis02':False,'apertura_formal_bis03':False,'perfil_integrado':'en','paridad_es_en_integrada':'pendiente','alcance':'Descriptor geométrico exacto y entrega documental local; sin imagen ni consumo visual de IA'};p.write_text(json.dumps(s,ensure_ascii=False,indent=2)+'\n')
p=r.L;s=p.read_text().replace('**Trabajo vigente: S22 / RETP-2026-216.','**Trabajo vigente: S22 / RETP-2026-218.')
start=s.index('**Siguiente objeto material:**');end=s.index('\n\n',start)
s=s[:start]+'''**Siguiente objeto material:** resolver las sedes e interfaz de recepción y observación del [recorrido integrado C02–C05](../paridad-imagen-celula-matematica/estudio-nucleo-agentes/integracion-c02-c05-v0_1/README.md), comprometido en RETP-218 con 26 casos (7 positivos y 19 negativos previstos), cero ejecutados y cuatro sensibilidades del observador aún pendientes. El contrato enlaza soporte, identidad, geometría y entrega, con guardas transversales. La [consolidación anterior](../paridad-imagen-celula-matematica/estudio-nucleo-agentes/consolidacion-bis-02/README.md) conserva su corte histórico. Sus 202 filas C02–C12 siguen sin ejecutar; los 24 originales conservan 2 ejecutados y 22 pendientes. Rust/Cargo 1.98.0 recuperados y comprobados en S25. BIS-02 abierto; BIS-03 sin apertura formal en este incremento. S24 conserva la GUI diferida.''' +s[end:];p.write_text(s)
shutil.copyfile(__file__,D/'soporte/registrar.py')
print(t)
