from pathlib import Path
from datetime import datetime,timezone
import json,hashlib
R=Path(__file__).resolve().parent;D=R/'entrega';L=R/'lectura';J=lambda p,x:p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n');sha=lambda b:hashlib.sha256(b).hexdigest();P='docs/calidad/tuberias-ia/';I=P+'integracion-adenda-ia-frame-y-catalogo-errores/'
fuentes=json.loads((D/'FUENTES_RECIBIDAS.json').read_text());pasajes=[]
def quote(id,path,start,end):
 text=(L/path).read_text();a=text.index(start);z=text.index(end,a)+len(end);a=text.rfind('\n',0,a)+1;z=text.find('\n',z) if '\n' in text[z:] else len(text)
 if z<len(text):z+=1
 b=text[a:z];pasajes.append(dict(id=id,ruta=path,linea_inicio=text[:a].count('\n')+1,linea_fin=text[:z].count('\n'),texto=b,sha256=sha(b.encode()),url=fuentes[path]['url']))
quote('B01','rust/sv_core/src/authority.rs','pub struct EffectDescriptor {','context: ContextRef,\n}')
quote('B02','rust/sv_core/src/authority.rs','pub fn contains_effect_scope','&& self.governs(effect.object())')
quote('B03','rust/sv_core/src/permission.rs','pub fn decide_permit(','let technical_result = aggregate_covered_requirement_results(requirements, resolved_results)?;')
quote('B04',P+'pertenencia-de-permisos-a-su-continuidad/README.md','El núcleo examinado aceptaba','antes de mediar o ejecutar.')
quote('B05','rust/sv_core/src/decision_trace.rs','pub fn mediate_traced_permit(','decision_trace: reference,\n    })\n}')
quote('B06',P+'recepcion-gobernada-y-comprobacion-observada/CONTRATO_Y_FRONTERA.md','La premisa usada en los tests','autoridad, forma, aplicabilidad y no autoacreditación.')
quote('B07',P+'recepcion-gobernada-y-comprobacion-observada/CONTRATO_Y_FRONTERA.md','El descriptor tiene que ser `Specific`.','Las obligaciones `Core` se rechazan siempre en esta vía.')
quote('B08','docs/calidad/CONTRATO_DE_CONSUMO_DOCUMENTAL_CYB_2026_09_09.md','### 8.3. Alcance y siguiente decisión','No es necesario resolver un despliegue real para continuar los contrastes documentales.')
quote('F01','rust/sv_core/src/execution.rs','/// Ejecuta una T-E mediada','pub fn execute_mediated<A: EffectExecutor>(')
quote('F02','rust/sv_core/src/execution.rs','let exercise = continuity.next_exercise_ref();','Err(ExecutionError::AdapterIndeterminate { exercise, error })')
quote('F03','rust/sv_core/src/execution.rs','/// Confirmación lógica local','pub struct ExerciseConfirmation {')
quote('F04',I+'s15-causas-recepcion/codigo/receptor.rs','if let Some(c)=fallo','match decodificar(&i.entrada){')
quote('K01',P+'recepcion-gobernada-y-comprobacion-observada/CONTRATO_Y_FRONTERA.md','Los estados son resultados técnicos','captura remota ni verdad del emisor.')
quote('G01',I+'G2_CORRESPONDENCIA_Y_LIMITE.md','## Decisión concreta','un nuevo adaptador que fabrique objetos.')
quote('G02',P+'WORKFLOW_ACOTADO_SUBORDINACION_IA_ES_V2_2026_09_11.md','**Cierre del análisis:**','no se declarará resuelta la segunda necesidad.')
quote('G03',P+'WORKFLOW_ACOTADO_SUBORDINACION_IA_ES_V2_2026_09_11.md','Una vez cerrado el recorrido trazable exigido','No se abren examen' if False else 'no las adelanta ni las cancela.')
quote('G04',I+'s13-suficiencia-semantica-ir/ACTA_SUFICIENCIA.md','1. **Transducción observación→Tri.**','no prueba comportamiento de un LLM frente a inyección ni autenticidad frente al host adversario.')
quote('G05','docs/calidad/REGISTRO_DEUDA_VIVA_DEL_FRENTE_FINAL_DEL_LENGUAJE_SV.md','Siguiente objeto C/I:','Ninguna garantía se cierra por esta revisión documental.')
J(D/'PASAJES_COTEJADOS.json',pasajes)
old=json.loads((L/(I+'s15-causas-recepcion/MATRIZ_COBERTURA_A_L_RESULTADO_S15.json')).read_text());criteria={c['id']:c for c in old['casos']}
rows=[
 dict(id='B',titulo='Facultad no concedida',sede='R1 y admisión competente exterior',existente=['ConstitutedAuthority liga titular, contexto, E_max y D_a; decide_permit recupera esos objetos y los requisitos.','Mediación y ejecución revalidan el compromiso. RETP-153 contiene una corrección candidata a pertenencia entre instancias.'],carencia='Raíz material admitida, productores de todos los requisitos y enlace profesional. La corrección de pertenencia sigue fuera del código main cotejado.',testigo='RETP-153 documenta permiso/compromiso de A aceptados en B con datos/ordinales iguales; se recibe como ensayo anterior. Una referencia o Accredited elegido no crea Permit.',positivo='Acto y alcance constituidos, comprobaciones gobernadas y token de la misma continuidad: sólo el efecto autorizado.',negativo='Afirmar una facultad, sustituir efecto, cambiar continuidad o aportar una comprobación declarada: rechazo anterior a efecto.',intervencion_minima='Recibir y verificar las candidatas de pertenencia y comprobación en su montaje; para producción, instalar admisión material y verificadores competentes. No constructor público ni conversión desde un recibo.',gate='No habilitar actuación profesional; conservar lectura documental.',respaldo=['B01','B02','B03','B04','B05','B06','B07','B08']),
 dict(id='E',titulo='Dependencia no autorizada de secreto',sede='Frontera material y canales declarados / P4',existente=['La matriz conserva el criterio de dos entradas con igual vista autorizada y variación exclusiva del secreto.','Registros estáticos o identidad de bytes pueden limitar un canal; no constituyen una prueba de no dependencia en otros.'],carencia='Vista autorizada, productor del estímulo secreto, canales observados y mecanismo material de aislamiento identificados para una operación concreta.',testigo='Dos ejecuciones podrían emitir el mismo diagnóstico visible y revelar el secreto por otro canal no observado. Es contraejemplo de diseño exigido, no un ataque ejecutado en S16.',positivo='Par con misma vista autorizada y salida permitida, canales y comparación fijados.',negativo='Variar sólo secreto o activar un canal de ensayo: detectar toda dependencia prohibida en los canales fijados.',intervencion_minima='Fijar contrato de vista/canales y observador material; ensayo en P4 al cumplirse su puerta, con control que demuestre que el observador detecta una fuga introducida.',gate='No afirmar confidencialidad/no interferencia global; P4 sigue pendiente.',respaldo=['G02','G03']),
 dict(id='K',titulo='Revisión efectiva de objeto y alcance',sede='Presentación y acto de revisión profesional',existente=['S15 conserva el diagnóstico escrito y su presentación textual de laboratorio.','PreparedExactCheck compara bytes observados con referencia y conserva evidencia; el contrato excluye acreditar procedencia física o acto profesional.'],carencia='Vínculo acreditado entre objeto realmente mostrado, alcance requerido, identidad/autoridad del revisor y acto de revisión. La misma cadena de caracteres no prueba qué vio una persona.',testigo='Nombre de revisor y hash pueden permanecer iguales aunque se muestre otro objeto o alcance. Contraejemplo de diseño, no suceso humano ejecutado.',positivo='Revisión sobre objeto efectivamente mostrado y alcance exacto, con acto y evidencia recuperables.',negativo='Objeto o alcance distintos manteniendo nombre del revisor; ausencia de acto: no acreditar revisión.',intervencion_minima='Enlazar presentación, objeto, alcance y acto en su frontera; el comparador de bytes sólo cubre igualdad cuando ésa sea la obligación recibida.',gate='No utilizar nombre, aprobación textual o comparación exacta como cierre profesional.',respaldo=['K01','B07','G02']),
 dict(id='L',titulo='Finalidad, destinatario y mínimo entregado',sede='Frontera de uso y efecto / P4 cuando proceda',existente=['EffectDescriptor y E_max ligan familia, objeto y contexto; R1 impone alcance constituido.','S2/S15 verifican cuerpo/citas/identidad documental. Estos controles no calculan por sí mismos finalidad ni mínimo autorizado.'],carencia='Regla constituida que seleccione el mínimo, destinatario admitido y puerto que imponga esa selección antes de entregar. El recorrido S15 no recibe esos contratos.',testigo='Cuerpo íntegro y correctamente citado enviado a un destinatario distinto sigue siendo entrega ajena. Integridad no satisface el criterio de destinatario.',positivo='Salida mínima conforme a finalidad y destinatario admitidos, con decisión previa y efecto observado.',negativo='Cambiar destinatario o añadir dato innecesario manteniendo cuerpo bien formado: bloquear antes de entregar.',intervencion_minima='Fijar el contrato de uso en dominio/ensamblaje, el verificador aplicable y el puerto de entrega; reutilizar ligaduras R1 sin atribuir autoridad a metadatos elegidos por la IA.',gate='No exponer entrega profesional hasta acreditar destinatario, mínimo y su imposición.',respaldo=['B01','B02','B03','B08','G03'])
]
for r in rows:
 r['criterio_original']=criteria[r['id']]['original_147'];r['estado']='REVISION_DOCUMENTAL_COMPLETADA_CAPACIDAD_INTEGRADA_NO_ACREDITADA';r['nueva_prueba_funcional']=False;r['extension_ir_justificada_en_este_corte']=False;r['limite_ir']='No se demuestra aquí pérdida de representación que obligue a extender IR; tampoco se acredita suficiencia para toda operación futura.'
J(D/'MATRIZ_FRONTERAS.json',dict(version='S16-FRONTERAS/1',filas=rows))
x=json.loads(json.dumps(old));x['version']='REVISION-COBERTURA-S16-RESULTADO/1';x['nota_s16']='Revisión B/E/K/L y fases de fallo; no ensayos nuevos ni cierre de capacidades.'
for c in x['casos']:c['resultado_s16']=dict(revision_documental=c['id'] in ['B','E','K','L'],estado='CARENCIA_Y_SEDE_LOCALIZADAS' if c['id'] in ['B','E','K','L'] else 'SIN_CAMBIO_DE_ALCANCE',ensayo_nuevo=False,cierre_universal=False)
assert [{k:v for k,v in c.items() if k!='resultado_s16'} for c in x['casos']]==old['casos'];J(D/'MATRIZ_COBERTURA_A_L_RESULTADO_S16.json',x)
J(D/'FRONTERAS_DE_FALLO.json',dict(version='S16-FASES-DE-FALLO/1',naturaleza='Contrato de correspondencia documental; no implementación ni ensayo nuevo.',filas=[
 dict(fase='Recepción anterior a cobertura',mecanismo='S15 recibir',observado='Error de Read y bytes parciales/completos conservados; cero llamadas a cobertura en F07-F09.',interpretacion='No se entregó cuerpo por este receptor; no describe un despacho profesional ni hechos exteriores.',respaldo=['F04']),
 dict(fase='Decisión de permiso',mecanismo='decide_permit',observado='NotGranted por RefutedRequirements/NotVerifiableRequirements, o error técnico de ligadura.',interpretacion='No forma permiso positivo; no se transforma en Tri.U ni acredita efecto.',respaldo=['B03']),
 dict(fase='Después de DispatchCommitted',mecanismo='execute_mediated / EffectExecutor',observado='Err del adaptador registra Indeterminate y AdapterIndeterminate; compromiso consumido.',interpretacion='No equivale a ausencia de efecto ni habilita reintento automático; exige recuperación aplicable.',respaldo=['F01','F02']),
 dict(fase='Confirmación local',mecanismo='ExerciseConfirmation',observado='Respuesta Ok del adaptador produce confirmación lógica local.',interpretacion='No es atestación independiente del mundo externo.',respaldo=['F03'])]))
T=datetime.now(timezone.utc).isoformat(timespec='seconds').replace('+00:00','Z');J(D/'CORTE_Y_ALCANCE.json',dict(version='S16-CORTE/1',fecha_cierre_documental_utc=T,cortes={k:json.loads((R/(k+'-base.json')).read_text()) for k in ['lenguaje','laboratorio']},resultado='Revisión completada; capacidades integradas B/E/K/L no acreditadas; no extensión IR propuesta.',fuentes=len(fuentes),pasajes=len(pasajes),fronteras=4,ensayos_funcionales_nuevos=0,siguiente_objeto='Consolidación del contrato del recorrido documental 1+3 y de sus límites de uso/diagnóstico, con matriz de causas realmente emitidas y distinción antes/después de despacho. No catálogo canónico completo ni P4 abierto.'))
print(len(rows),'fronteras;',len(pasajes),'pasajes; cero ensayos funcionales nuevos.')
