# ES: Registra exclusivamente resultados efectivamente observados.
# EN: Records only results actually observed.
from pathlib import Path
import sys,json
sys.path.insert(0,'bis-c02');import registro as r
E=r.B/'bis04-extension-perfiles-recursos-v0_1';C=Path('bis-extension/reproduccion-r01/ejecucion');summary=json.loads((C/'resultados/RESUMEN.json').read_text());assert summary=={'integrados':26,'comparaciones_paridad':5,'fallos':0}
t=r.now();fields,rs=r.rows();row=next(x for x in rs if x['id']=='S22');assert row['estado']=='en ejecución'
row.update(fecha_actualizacion_utc=t,cortes_de_entrada='Lenguaje aa1229788f0a6625be43c74e29c38023b8193a4c; laboratorio ed5a78fb667401b052e915db38bf17465fe3b2b2',resultado='Extensión nativa del montaje C02–C05: 26 casos nuevos conformes (9 entregas documentales, 17 rechazos), con perfiles ES/EN, cuotas de recepción/recibo y captura. Cinco comparaciones canónicas conformes en campaña R01: cuatro equivalencias y una desigualdad por cambio de dato textual. Núcleo sv_core y admisión RETP-220 sin modificaciones.',verificacion='Precompromiso en laboratorio y espejo antes de cada ejecución. Cargo build --locked --offline y binario nativo Rust/Cargo 1.98.0 desde directorios nuevos; contadores reales por canal, recibos completos, captura, trazas y estados conservados. Dos campañas: 52 invocaciones integradas, 26 variantes únicas. Primera campaña: 26 conformes y tres comparaciones impedidas por Celda, identificador protegido en fixtures C12. Fallo conservado; variantes nuevas CeldaPrueba, previamente comprometidas, resuelven las tres comparaciones sin cambiar expectativas ni compilador.',evidencias='https://github.com/juantoniolloretegea/SV-lenguaje-de-computacion/blob/main/'+str(E.relative_to(r.R))+'/README.md',referencia_calidad='https://github.com/juantoniolloretegea/SV-lenguaje-de-computacion/blob/main/docs/calidad/REGISTRO_EVOLUCION_TECNICA_PROYECTO.md#retp-221',siguiente_accion='Completar frontera de tamaño del descriptor y salida agregada del montaje, y preparar su relevo hacia representación/consumo con pruebas previas; trasladar el hallazgo Celda al retorno de documentación/errores. Mantener Bis → catálogo y cierre de fase → análisis e instalación de GUI.',observaciones='BIS-02/BIS-03/BIS-04 globales abiertos. Paridad acreditada para estas fuentes y operaciones, sin garantía universal ni consumo visual de IA. Cuotas de memoria/tiempo y agotamiento no constituidos. Las 202 filas originales C02–C12 no se declaran ejecutadas como banco propio; originales C12 y resultados previos intactos. S24/GUI diferida; S25 conservado.')
r.guardar(fields,rs,row);r.retp(221,'S22 · Extensión ES/EN, recursos y captura; hallazgo léxico C12',t,row,str(E.relative_to(r.R/'docs/calidad'))+'/README.md','EXTENSION_EXPERIMENTAL_Y_VERIFICACION_NATIVA','Workflow V2; RETP-218 a 220; banco previo y variantes R01 fijados antes de ejecutar','Paridad y controles acotados acreditados; defecto de fixture conservado, sin cierre global')
p=r.B/'ESTADO_WORKFLOW.json';s=json.loads(p.read_text());s.update(ultimo_retp='RETP-2026-221',ultimo_informe='bis04-extension-perfiles-recursos-v0_1/README.md',siguiente_accion=row['siguiente_accion'])
s['integracion_c02_c05']['paridad_es_en_integrada']='Acreditada en la extensión RETP-221 para las fuentes sintéticas ensayadas; no suficiencia universal C12.'
s['extension_bis04_perfiles_recursos']={'registro':'RETP-2026-221','informe':'bis04-extension-perfiles-recursos-v0_1/README.md','integrados_unicos':26,'campanas':2,'invocaciones_admision':52,'integrados_conformes_cada_campana':26,'entregas_cada_campana':9,'rechazos_cada_campana':17,'comparaciones_paridad_campana_01':{'conformes':2,'impedidas_por_fixture':3},'comparaciones_paridad_r01':{'conformes':5,'equivalencias':4,'desigualdades':1},'variantes_paridad_nuevas_r01':3,'originales_c12_modificados':False,'admision_y_nucleo_modificados':False,'suficiencia_global':False,'hallazgo':'Celda es palabra protegida y no puede nombrar el fixture; variantes nuevas CeldaPrueba conservan el contenido.'}
for e in s['etapas']:
 if e['id']=='BIS-04':e['alcance']='Montaje experimental C02–C05 y extensión ES/EN/recursos/captura ensayados en Rust; fase global abierta.'
p.write_text(json.dumps(s,ensure_ascii=False,indent=2)+'\n')
p=r.L;text=p.read_text().replace('**Trabajo vigente: S22 / RETP-2026-220.','**Trabajo vigente: S22 / RETP-2026-221.');a=text.index('**Siguiente objeto material:**');b=text.index('\n\n',a)
text=text[:a]+'''**Siguiente objeto material:** completar las fronteras de descriptor/salida agregada y preparar el relevo de representación/consumo del montaje. La [extensión ES/EN, recursos y captura](../paridad-imagen-celula-matematica/estudio-nucleo-agentes/bis04-extension-perfiles-recursos-v0_1/README.md), RETP-221, añade 26 casos nativos conformes y cinco comparaciones canónicas finales conformes. Conserva la primera campaña con tres comparaciones impedidas por el identificador protegido `Celda`; variantes nuevas `CeldaPrueba`, fijadas antes de repetir, resuelven ese defecto de fixture. Núcleo y admisión anteriores intactos. BIS-02/BIS-03/BIS-04 globales abiertos; 202 filas originales C02–C12 sin ejecutar como banco propio, 24 escenarios originales (2 ejecutados y 22 pendientes) y 13 variantes C01 conservados. S24/GUI diferida hasta Bis, catálogo y cierre de fase; S25 conservado.''' +text[b:];p.write_text(text)
print(t)
