"""Registra R05 y continuidad; no ejecuta sondas. Uso desde checkout: gestionar.py previo|resultado."""
from pathlib import Path
import json,sys,datetime,subprocess,hashlib
R=Path.cwd();E=Path(__file__).resolve().parent;stage=sys.argv[1];assert stage in ('previo','resultado');num=231 if stage=='previo' else 232
if stage=='previo':
 result='R05: siete sondas previas fijadas para retorno rechazado, ausencia de captura, pánico y sustitución de ruta tras apertura. Copia local instrumentada; sin cambio productivo.'
 verification='Banco y 25 archivos fijados antes de Cargo; fuentes R04 conservadas. Precompromiso público y espejo preceden a campaña.'
 next_action='Ejecutar siete sondas R05; conservar lecturas reales, informes ausentes y sustitución de objeto con bytes iguales sin promover garantías.'
else:
 x=json.loads((E/'RESULTADOS.json').read_text());assert x['sondas_aprobadas']==7 and x['sondas_fallidas']==0
 result='R05: siete sondas conformes al banco. Rechazo y falta de captura permiten relectura sin acreditar entrega. Pánico impide MaterialRun final. Ruta sustituida con bytes iguales conserva concordancia pese a cambio de objeto: límite confirmado.'
 verification='Una campaña Rust/Cargo 1.98.0 offline; siete aserciones de caso conformes, fuentes y precompromiso intactos; dos pánicos provocados y capturados sólo por el arnés. Sin protección productiva ante pánico acreditada.'
 next_action='Definir recepción explícita de terminación sin informe y alcance de identidad de fuente antes de integrar; después cualificar abort/interrupción de proceso y montaje completo. S26 permanece abierto; conservar Bis/S24.'
now=datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ');base='Lenguaje 32410645663ea198516803afb88cf5195b584676; laboratorio 58de66b3dfba33a934da535ab341d66b3ca274c9';url='https://github.com/juantoniolloretegea/SV-lenguaje-de-computacion/blob/main/'
seat=dict(suceso=dict(id='S26',fecha_actualizacion_utc=now,cortes_de_entrada=base,resultado=result,verificacion=verification,siguiente_accion=next_action,evidencias=url+'docs/calidad/riesgos-materiales-s26/r05/README.md',referencia_calidad=url+f'docs/calidad/REGISTRO_EVOLUCION_TECNICA_PROYECTO.md#retp-{num}',observaciones='S26 sigue en ejecución; doce casos globales abiertos. S22/S24 y banco Bis intactos. Ensayo Linux local sin BD, transacción durable, adquisición, GUI, fallo de hardware ni resistencia al host acreditados. Inode local no es identidad universal. S27 conserva reparto dominio/agente/Lenguaje.'),revision=8 if stage=='previo' else 9,retp=num,tipo='BANCO_PREVIO' if stage=='previo' else 'CONTRASTE_MATERIAL_ACOTADO',motivo='Continuación autorizada tras incorporación documental de rutas.',base=base,artefactos='S26 R05; código íntegro y diferencia, fuentes, banco, evidencia; Sucesos/RETP y navegación.',impacto='Cualificación local; ninguna promoción productiva.',titulo='R05 '+stage)
p=E/('ASIENTO_'+stage+'.json');p.write_text(json.dumps(seat,ensure_ascii=False,indent=2)+'\n');subprocess.run(['python',str(E.parent/'soporte/registrar_continuacion.py'),str(p)],check=True)
for p,link in [(E.parent/'README.md','r05/README.md'),(R/'docs/calidad/tuberias-ia/frame-significado-humano-trazabilidad-y-fidelidad/LEAME_PRIMERO.md','../../riesgos-materiales-s26/r05/README.md')]:
 p.write_text(p.read_text()+f'\n## S26 R05 · RETP-{num}\n\n'+result+' '+next_action+' [Banco y evidencia]('+link+').\n')
p=R/'docs/calidad/tuberias-ia/paridad-imagen-celula-matematica/estudio-nucleo-agentes/ESTADO_WORKFLOW.json';j=json.loads(p.read_text());j['seguimiento_transversal_s26'].update(registro=f'RETP-2026-{num}',campana_r05='../../../riesgos-materiales-s26/r05/README.md',sondas_r05_previstas=7,sondas_r05_ejecutadas=0 if stage=='previo' else 7,casos_globales_cerrados=0,siguiente_accion=next_action);p.write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n')
v=R/'docs/calidad/tuberias-ia/frame-significado-humano-trazabilidad-y-fidelidad';p=v/'MANIFIESTO.json';j=json.loads(p.read_text());b=(v/'LEAME_PRIMERO.md').read_bytes();j['archivos']['LEAME_PRIMERO.md']=dict(bytes=len(b),sha256=hashlib.sha256(b).hexdigest(),git_blob_sha1=hashlib.sha1(b'blob '+str(len(b)).encode()+b'\0'+b).hexdigest());j['actualizaciones'].append(dict(fecha=now[:10],registro=f'RETP-2026-{num}',alcance='Navegación a S26 R05 '+stage+'; PDF/MD sustantivos conservados.'));p.write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n')
